const graphData = {
  "nodes": [
    {"id": "Data center Cézanne — Sybilles", "label": "Data center\nCézanne\nSybilles", "group": "Projet central", "size": 34, "detail": "Projet Telehouse / KDDI dans la zone des Sybilles, aux Pennes-Mirabeau, à proximité de Saint-Victoret."}, 
    {"id": "Collectif Non au data center", "label": "Collectif\n« Non au\ndata center »", "group": "Noyau d’opposition local", "size": 25, "detail": "Collectif d’habitants opposé au projet Telehouse ; maintient le recours et demande davantage de garanties."}, 
    {"id": "CIQ des Pallières", "label": "CIQ des\nPallières", "group": "Noyau d’opposition local", "size": 23, "detail": "Comité d’intérêt de quartier des Pennes-Mirabeau, partie prenante du recours collectif contre le permis de construire."}, 
    {"id": "CIQ Sybilles-Amphoux", "label": "CIQ\nSybilles-\nAmphoux", "group": "Noyau d’opposition local", "size": 23, "detail": "Comité d’intérêt de quartier de Saint-Victoret, mobilisé contre les nuisances, la chaleur fatale, le risque incendie et le manque de garanties."}, 
    {"id": "Habitants pennois et saint-victoriens", "label": "Habitants\npennois &\nsaint-victoriens", "group": "Noyau d’opposition local", "size": 21, "detail": "Riverains mobilisés dans le recours collectif ; contestent l’absence de concertation, les risques environnementaux et les nuisances."}, 
    {"id": "Associations environnementales", "label": "Associations\nenvironne-\nmentales", "group": "Noyau d’opposition local", "size": 17, "detail": "Mentionnées comme parties prenantes du recours collectif, sans noms explicitement détaillés dans le corpus."}, 
    {"id": "Martine Mezzo", "label": "Martine\nMezzo", "group": "Opposants nommés", "size": 20, "detail": "Représentante du collectif « Non au data center » ; affirme que le collectif ne retirera pas son recours."}, 
    {"id": "Christine Muscat", "label": "Christine\nMuscat", "group": "Opposants nommés", "size": 20, "detail": "Présidente du CIQ des Pallières ; maintient le recours pour être entendue, obtenir des réponses et contester le projet en l’état."}, 
    {"id": "Christel Fayette", "label": "Christel\nFayette", "group": "Opposants nommés", "size": 19, "detail": "Présidente du CIQ Sybilles-Amphoux ; alerte sur les travaux, l’excavation, la chaleur fatale et les risques sanitaires."}, 
    {"id": "Hervé Plisson", "label": "Hervé\nPlisson", "group": "Opposants nommés", "size": 18, "detail": "Habitant de Bouc-Bel-Air ; critique la rapidité des projets, le déséquilibre du rapport de force et l’appui gouvernemental aux opérateurs."}, 
    {"id": "Patrick Robert", "label": "Patrick\nRobert", "group": "Opposants nommés", "size": 18, "detail": "Vice-président de la fédération des CIQ du 16e arrondissement de Marseille ; alerte sur l’empressement des procédures et les conflits d’usage électriques."}, 
    {"id": "Arthur", "label": "Arthur", "group": "Opposants nommés", "size": 17, "detail": "Militant engagé contre le projet de Gardanne ; critique le modèle de société porté par les data centers et les usages jugés non essentiels."}, 
    {"id": "Antoine Devillet", "label": "Antoine\nDevillet", "group": "Opposants nommés", "size": 19, "detail": "Membre du Nuage était sous nos pieds ; insiste sur les enquêtes publiques, la bataille culturelle, le moratoire et une convention citoyenne numérique."}, 
    {"id": "Laure", "label": "Laure", "group": "Opposants nommés", "size": 14, "detail": "Citoyenne rencontrée lors d’une balade du Nuage était sous nos pieds ; exprime un intérêt pour l’engagement."}, 
    {"id": "Jean-Claude", "label": "Jean-\nClaude", "group": "Opposants nommés", "size": 15, "detail": "Habitant cité aux Pennes-Mirabeau ; doute des bénéfices du projet et alerte sur la consommation d’électricité et d’eau."}, 
    {"id": "Vanessa", "label": "Vanessa", "group": "Opposants nommés", "size": 15, "detail": "Habitante citée ; s’inquiète de l’urbanisation, de l’esprit village et de l’îlot de chaleur pouvant toucher les habitations."}, 
    {"id": "Romain Amaro", "label": "Romain\nAmaro", "group": "Élus critiques ou opposés", "size": 25, "detail": "Maire DVD des Pennes-Mirabeau ; s’est dit farouchement contre le projet en l’état, mais se heurte au risque juridique et financier d’un retrait du permis."}, 
    {"id": "Claude Piccirillo", "label": "Claude\nPiccirillo", "group": "Élus critiques ou opposés", "size": 22, "detail": "Maire de Saint-Victoret ; dépose un recours pour obtenir des certitudes sur l’alimentation électrique, les rejets d’eau et les conditions d’implantation."}, 
    {"id": "Éric Leotard", "label": "Éric\nLeotard", "group": "Élus critiques ou opposés", "size": 19, "detail": "Premier adjoint de Saint-Victoret ; alerte sur la santé, la tranquillité, la sécurité, les inondations, le paysage et les lignes à haute tension."}, 
    {"id": "Pierre Gelsi", "label": "Pierre\nGelsi", "group": "Élus critiques ou opposés", "size": 18, "detail": "Élu d’opposition à Saint-Victoret, ancien président du CIQ Sybilles-Amphoux ; estime que le data center n’a rien à faire dans un secteur d’habitat et d’agriculture."}, 
    {"id": "Hervé Fabre-Aubrespy", "label": "Hervé\nFabre-\nAubrespy", "group": "Élus critiques ou opposés", "size": 17, "detail": "Candidat RN ; annonce qu’il attaquera le permis si le préfet l’accorde et critique l’absence d’accord des habitants."}, 
    {"id": "Maximilien Fusone", "label": "Maximilien\nFusone", "group": "Élus critiques ou opposés", "size": 16, "detail": "Rassemblement pennois ; se déclare contre le projet et invoque le principe de précaution."}, 
    {"id": "PCF des Pennes-Mirabeau", "label": "PCF des\nPennes-\nMirabeau", "group": "Élus critiques ou opposés", "size": 16, "detail": "Les communistes locaux s’associent au questionnement du CIQ des Pallières et demandent transparence et étude alternative."}, 
    {"id": "Michel Amiel", "label": "Michel\nAmiel", "group": "Élus favorables / prudents", "size": 19, "detail": "Ancien maire des Pennes-Mirabeau ; a signé le permis de construire avant les élections, ce qui cristallise une partie des critiques."}, 
    {"id": "Grégory Bouchet", "label": "Grégory\nBouchet", "group": "Élus favorables / prudents", "size": 18, "detail": "Candidat SE / majorité sortante ; seul candidat explicitement favorable dans le débat municipal, au nom des emplois et recettes communales."}, 
    {"id": "Jean-Philippe Musso", "label": "Jean-Philippe\nMusso", "group": "Élus favorables / prudents", "size": 17, "detail": "Candidat DVG / ancien adjoint aux finances ; plutôt favorable à un data center mais dans un autre secteur de la commune."}, 
    {"id": "Laurent Simon", "label": "Laurent\nSimon", "group": "Élus favorables / prudents", "size": 16, "detail": "Président de la SPL Énergies de Provence et maire de Plan-de-Cuques ; intéressé par le réseau de chaleur, tout en jugeant qu’il est trop tôt pour conclure."}, 
    {"id": "Jean-Charles Lamathe", "label": "Jean-Charles\nLamathe", "group": "Élus favorables / prudents", "size": 14, "detail": "Quatrième adjoint aux Pennes-Mirabeau ; cité sur le débat budgétaire, sans position centrale détaillée sur le data center."}, 
    {"id": "Sandrine Gras-Trubert", "label": "Sandrine\nGras-Trubert", "group": "Élus favorables / prudents", "size": 14, "detail": "Conseillère municipale d’opposition ; intervient sur les délégations sécurité et transition écologique, sans opposition détaillée au projet."}, 
    {"id": "Telehouse", "label": "Telehouse", "group": "Acteurs institutionnels / techniques", "size": 25, "detail": "Porteur du projet Cézanne aux Sybilles ; filiale du groupe japonais KDDI, huit bâtiments prévus sur environ six hectares."}, 
    {"id": "KDDI", "label": "KDDI", "group": "Acteurs institutionnels / techniques", "size": 18, "detail": "Groupe japonais propriétaire de Telehouse ; acteur industriel indirect du projet."}, 
    {"id": "RTE", "label": "RTE", "group": "Acteurs institutionnels / techniques", "size": 19, "detail": "Intervient sur le raccordement électrique ; mention d’un enfouissement total des lignes selon les échanges rapportés."}, 
    {"id": "ARS", "label": "ARS", "group": "Acteurs institutionnels / techniques", "size": 15, "detail": "Citée par les riverains sur les risques sanitaires dans un territoire déjà pollué."}, 
    {"id": "SDIS", "label": "SDIS", "group": "Acteurs institutionnels / techniques", "size": 15, "detail": "A émis un avis favorable malgré les inquiétudes sur le risque incendie."}, 
    {"id": "SPL Énergies de Provence", "label": "SPL Énergies\nde Provence", "group": "Acteurs institutionnels / techniques", "size": 17, "detail": "Société publique locale sollicitée pour réfléchir à un réseau de récupération de chaleur fatale."}, 
    {"id": "SPLA Pays d’Aix Territoires", "label": "SPLA Pays\nd’Aix\nTerritoires", "group": "Acteurs institutionnels / techniques", "size": 15, "detail": "Structure impliquée dans la cession initiale du terrain avant sa revente à Telehouse."}, 
    {"id": "Préfecture / État", "label": "Préfecture\n/ État", "group": "Acteurs institutionnels / techniques", "size": 17, "detail": "Cadre administratif et décisionnel ; mention du risque que le préfet ferme la possibilité de négociation."}, 
    {"id": "Tribunal administratif de Marseille", "label": "Tribunal\nadministratif\nde Marseille", "group": "Acteurs institutionnels / techniques", "size": 18, "detail": "Instance saisie par le recours de Saint-Victoret et par le recours collectif des CIQ/habitants."}, 
    {"id": "Le Nuage était sous nos pieds", "label": "Le Nuage\nétait sous\nnos pieds", "group": "Réseau élargi anti-data centers", "size": 23, "detail": "Collectif marseillais critique des data centers ; enquête, formations, balades urbaines, bataille culturelle et demande de moratoire."}, 
    {"id": "Data for Good", "label": "Data for\nGood", "group": "Réseau élargi anti-data centers", "size": 17, "detail": "Collectif venant en support des oppositions locales, notamment sur les analyses et failles juridiques."}, 
    {"id": "France Nature Environnement", "label": "France Nature\nEnvironnement", "group": "Réseau élargi anti-data centers", "size": 17, "detail": "Réseau cité comme appui aux collectifs pour chercher des failles juridiques dans les permis et documents d’urbanisme."}, 
    {"id": "Collectifs de Gardanne", "label": "Collectifs de\nGardanne", "group": "Réseau élargi anti-data centers", "size": 16, "detail": "Mobilisations liées à la reconversion industrielle d’une écoplateforme pouvant accueillir un data center."}, 
    {"id": "Collectifs de Bouc-Bel-Air", "label": "Collectifs de\nBouc-Bel-Air", "group": "Réseau élargi anti-data centers", "size": 16, "detail": "Mobilisations autour du projet Digital Realty MRS6, avec inquiétudes sur l’environnement et les nuisances."}, 
    {"id": "Collectifs Marseille nord / Estaque", "label": "Collectifs\nMarseille nord\n/ Estaque", "group": "Réseau élargi anti-data centers", "size": 16, "detail": "Mobilisations liées aux projets de data centers dans le 16e arrondissement et aux conflits d’usage électriques."}, 
    {"id": "La Provence", "label": "La Provence", "group": "Médias / relais / lieux cités", "size": 17, "detail": "Média local ayant suivi le dossier électoral, les recours, les positions d’élus et les tensions autour de Telehouse."}, 
    {"id": "Marsactu", "label": "Marsactu", "group": "Médias / relais / lieux cités", "size": 16, "detail": "Média local d’investigation ; cité sur les fuites de gaz fluorés et le recours fragilisant les plans du maire."}, 
    {"id": "L’ADN", "label": "L’ADN", "group": "Médias / relais / lieux cités", "size": 15, "detail": "Média ayant publié le reportage sur Marseille, hub mondial et luttes locales."}, 
    {"id": "France 3 Provence-Alpes-Côte d’Azur", "label": "France 3\nPACA", "group": "Médias / relais / lieux cités", "size": 16, "detail": "Média ayant couvert la résistance d’élus et de riverains aux Pennes-Mirabeau / Saint-Victoret."}, 
    {"id": "Mucem", "label": "Mucem", "group": "Médias / relais / lieux cités", "size": 15, "detail": "Institution culturelle ayant abandonné son partenariat avec Digital Realty sous pression du Nuage était sous nos pieds."}, 
    {"id": "Grand Port Maritime de Marseille", "label": "Grand Port\nMaritime de\nMarseille", "group": "Médias / relais / lieux cités", "size": 16, "detail": "Acteur cité dans les conflits d’usage électriques, notamment autour de l’électrification des quais."}, 
    {"id": "Philippe Chabeaudy", "label": "Philippe\nChabeaudy", "group": "Opposants nommés", "size": 15, "detail": "Habitant des Pennes-Mirabeau, redoute le risque d'incendie du data center Cézanne."},
    {"id": "Lou Welgryn", "label": "Lou Welgryn", "group": "Réseau élargi anti-data centers", "size": 15, "detail": "Coprésidente de Data for Good, critique le gigantisme sans stratégie."},
    {"id": "Cécile Diguet", "label": "Cécile Diguet", "group": "Réseau élargi anti-data centers", "size": 15, "detail": "Urbaniste, pointe l'incompatibilité avec les stratégies environnementales locales."},
    {"id": "Maxime Colin", "label": "Maxime Colin", "group": "Réseau élargi anti-data centers", "size": 15, "detail": "Juriste à France Nature Environnement, dénonce une législation de plus en plus permissive."},
    {"id": "Maxime Efoui-Hess", "label": "Maxime\nEfoui-Hess", "group": "Réseau élargi anti-data centers", "size": 15, "detail": "Membre du Shift Project, alerte sur les conflits d'usage électrique."},
    {"id": "Shift Project", "label": "Shift Project", "group": "Réseau élargi anti-data centers", "size": 17, "detail": "Think tank soulignant les risques liés à la priorisation énergétique des data centers."},
    {"id": "Associations de Wissous", "label": "Associations\nWissous", "group": "Réseau élargi anti-data centers", "size": 15, "detail": "Collectifs menant une action en justice contre le saucissonnage de projets."},
    {"id": "France Datacenter", "label": "France\nDatacenter", "group": "Acteurs institutionnels / techniques", "size": 17, "detail": "Association représentant la filière professionnelle des data centers."},
    {"id": "Michaël Reffay", "label": "Michaël Reffay", "group": "Acteurs institutionnels / techniques", "size": 15, "detail": "Délégué général de France Datacenter, défend l'utilité économique des projets."},
    {"id": "Ademe", "label": "Ademe", "group": "Acteurs institutionnels / techniques", "size": 17, "detail": "Agence prévoyant le quadruplement de la consommation électrique de ces infrastructures."},
    {"id": "Gouvernement français", "label": "Gouvernement\nfrançais", "group": "Acteurs institutionnels / techniques", "size": 19, "detail": "Soutient les investissements massifs dans les giga data centers."},
    {"id": "EDF", "label": "EDF", "group": "Acteurs institutionnels / techniques", "size": 17, "detail": "Énergéticien qui a besoin des data centers comme relais de croissance selon la filière."},
    {"id": "news.google.com", "label": "news.google.com", "group": "Médias / relais / lieux cités", "size": 15, "detail": "Agrégateur ayant relayé l'analyse nationale sur les tensions liées aux data centers."}
  ],
  "links": [
    {"source": "Data center Cézanne — Sybilles", "target": "Collectif Non au data center", "kind": "position / rôle"}, 
    {"source": "Data center Cézanne — Sybilles", "target": "CIQ des Pallières", "kind": "position / rôle"}, 
    {"source": "Data center Cézanne — Sybilles", "target": "CIQ Sybilles-Amphoux", "kind": "position / rôle"}, 
    {"source": "Data center Cézanne — Sybilles", "target": "Habitants pennois et saint-victoriens", "kind": "position / rôle"}, 
    {"source": "Data center Cézanne — Sybilles", "target": "Associations environnementales", "kind": "position / rôle"}, 
    {"source": "Data center Cézanne — Sybilles", "target": "Martine Mezzo", "kind": "position / rôle"}, 
    {"source": "Data center Cézanne — Sybilles", "target": "Christine Muscat", "kind": "position / rôle"}, 
    {"source": "Data center Cézanne — Sybilles", "target": "Christel Fayette", "kind": "position / rôle"}, 
    {"source": "Data center Cézanne — Sybilles", "target": "Hervé Plisson", "kind": "position / rôle"}, 
    {"source": "Data center Cézanne — Sybilles", "target": "Patrick Robert", "kind": "position / rôle"}, 
    {"source": "Data center Cézanne — Sybilles", "target": "Arthur", "kind": "position / rôle"}, 
    {"source": "Data center Cézanne — Sybilles", "target": "Antoine Devillet", "kind": "position / rôle"}, 
    {"source": "Data center Cézanne — Sybilles", "target": "Laure", "kind": "position / rôle"}, 
    {"source": "Data center Cézanne — Sybilles", "target": "Jean-Claude", "kind": "position / rôle"}, 
    {"source": "Data center Cézanne — Sybilles", "target": "Vanessa", "kind": "position / rôle"}, 
    {"source": "Data center Cézanne — Sybilles", "target": "Romain Amaro", "kind": "position / rôle"}, 
    {"source": "Data center Cézanne — Sybilles", "target": "Claude Piccirillo", "kind": "position / rôle"}, 
    {"source": "Data center Cézanne — Sybilles", "target": "Éric Leotard", "kind": "position / rôle"}, 
    {"source": "Data center Cézanne — Sybilles", "target": "Pierre Gelsi", "kind": "position / rôle"}, 
    {"source": "Data center Cézanne — Sybilles", "target": "Hervé Fabre-Aubrespy", "kind": "position / rôle"}, 
    {"source": "Data center Cézanne — Sybilles", "target": "Maximilien Fusone", "kind": "position / rôle"}, 
    {"source": "Data center Cézanne — Sybilles", "target": "PCF des Pennes-Mirabeau", "kind": "position / rôle"}, 
    {"source": "Data center Cézanne — Sybilles", "target": "Michel Amiel", "kind": "position / rôle"}, 
    {"source": "Data center Cézanne — Sybilles", "target": "Grégory Bouchet", "kind": "position / rôle"}, 
    {"source": "Data center Cézanne — Sybilles", "target": "Jean-Philippe Musso", "kind": "position / rôle"}, 
    {"source": "Data center Cézanne — Sybilles", "target": "Laurent Simon", "kind": "position / rôle"}, 
    {"source": "Data center Cézanne — Sybilles", "target": "Jean-Charles Lamathe", "kind": "position / rôle"}, 
    {"source": "Data center Cézanne — Sybilles", "target": "Sandrine Gras-Trubert", "kind": "position / rôle"}, 
    {"source": "Data center Cézanne — Sybilles", "target": "Telehouse", "kind": "position / rôle"}, 
    {"source": "Data center Cézanne — Sybilles", "target": "KDDI", "kind": "position / rôle"}, 
    {"source": "Data center Cézanne — Sybilles", "target": "RTE", "kind": "position / rôle"}, 
    {"source": "Data center Cézanne — Sybilles", "target": "ARS", "kind": "position / rôle"}, 
    {"source": "Data center Cézanne — Sybilles", "target": "SDIS", "kind": "position / rôle"}, 
    {"source": "Data center Cézanne — Sybilles", "target": "SPL Énergies de Provence", "kind": "position / rôle"}, 
    {"source": "Data center Cézanne — Sybilles", "target": "SPLA Pays d’Aix Territoires", "kind": "position / rôle"}, 
    {"source": "Data center Cézanne — Sybilles", "target": "Préfecture / État", "kind": "position / rôle"}, 
    {"source": "Data center Cézanne — Sybilles", "target": "Tribunal administratif de Marseille", "kind": "position / rôle"}, 
    {"source": "Data center Cézanne — Sybilles", "target": "Le Nuage était sous nos pieds", "kind": "position / rôle"}, 
    {"source": "Data center Cézanne — Sybilles", "target": "Data for Good", "kind": "position / rôle"}, 
    {"source": "Data center Cézanne — Sybilles", "target": "France Nature Environnement", "kind": "position / rôle"}, 
    {"source": "Data center Cézanne — Sybilles", "target": "Collectifs de Gardanne", "kind": "position / rôle"}, 
    {"source": "Data center Cézanne — Sybilles", "target": "Collectifs de Bouc-Bel-Air", "kind": "position / rôle"}, 
    {"source": "Data center Cézanne — Sybilles", "target": "Collectifs Marseille nord / Estaque", "kind": "position / rôle"}, 
    {"source": "Martine Mezzo", "target": "Collectif Non au data center", "kind": "rattachement / interaction"}, 
    {"source": "Christine Muscat", "target": "CIQ des Pallières", "kind": "rattachement / interaction"}, 
    {"source": "Christel Fayette", "target": "CIQ Sybilles-Amphoux", "kind": "rattachement / interaction"}, 
    {"source": "Pierre Gelsi", "target": "CIQ Sybilles-Amphoux", "kind": "rattachement / interaction"}, 
    {"source": "Claude Piccirillo", "target": "Tribunal administratif de Marseille", "kind": "rattachement / interaction"}, 
    {"source": "CIQ des Pallières", "target": "Tribunal administratif de Marseille", "kind": "rattachement / interaction"}, 
    {"source": "CIQ Sybilles-Amphoux", "target": "Tribunal administratif de Marseille", "kind": "rattachement / interaction"}, 
    {"source": "Collectif Non au data center", "target": "Tribunal administratif de Marseille", "kind": "rattachement / interaction"}, 
    {"source": "Romain Amaro", "target": "Telehouse", "kind": "rattachement / interaction"}, 
    {"source": "Romain Amaro", "target": "RTE", "kind": "rattachement / interaction"}, 
    {"source": "Romain Amaro", "target": "SPL Énergies de Provence", "kind": "rattachement / interaction"}, 
    {"source": "Telehouse", "target": "KDDI", "kind": "rattachement / interaction"}, 
    {"source": "Telehouse", "target": "RTE", "kind": "rattachement / interaction"}, 
    {"source": "Telehouse", "target": "SPLA Pays d’Aix Territoires", "kind": "rattachement / interaction"}, 
    {"source": "Telehouse", "target": "SDIS", "kind": "rattachement / interaction"}, 
    {"source": "Telehouse", "target": "ARS", "kind": "rattachement / interaction"}, 
    {"source": "Claude Piccirillo", "target": "Éric Leotard", "kind": "rattachement / interaction"}, 
    {"source": "Collectif Non au data center", "target": "CIQ des Pallières", "kind": "rattachement / interaction"}, 
    {"source": "Collectif Non au data center", "target": "CIQ Sybilles-Amphoux", "kind": "rattachement / interaction"}, 
    {"source": "Collectif Non au data center", "target": "Habitants pennois et saint-victoriens", "kind": "rattachement / interaction"}, 
    {"source": "PCF des Pennes-Mirabeau", "target": "CIQ des Pallières", "kind": "rattachement / interaction"}, 
    {"source": "Antoine Devillet", "target": "Le Nuage était sous nos pieds", "kind": "rattachement / interaction"}, 
    {"source": "Le Nuage était sous nos pieds", "target": "Data for Good", "kind": "rattachement / interaction"}, 
    {"source": "Le Nuage était sous nos pieds", "target": "France Nature Environnement", "kind": "rattachement / interaction"}, 
    {"source": "Le Nuage était sous nos pieds", "target": "Mucem", "kind": "rattachement / interaction"}, 
    {"source": "Patrick Robert", "target": "Collectifs Marseille nord / Estaque", "kind": "rattachement / interaction"}, 
    {"source": "Hervé Plisson", "target": "Collectifs de Bouc-Bel-Air", "kind": "rattachement / interaction"}, 
    {"source": "Arthur", "target": "Collectifs de Gardanne", "kind": "rattachement / interaction"}, 
    {"source": "Grand Port Maritime de Marseille", "target": "Collectifs Marseille nord / Estaque", "kind": "rattachement / interaction"}, 
    {"source": "Data center Cézanne — Sybilles", "target": "La Provence", "kind": "couverture médiatique"}, 
    {"source": "Data center Cézanne — Sybilles", "target": "Marsactu", "kind": "couverture médiatique"}, 
    {"source": "Data center Cézanne — Sybilles", "target": "L’ADN", "kind": "couverture médiatique"}, 
    {"source": "Data center Cézanne — Sybilles", "target": "France 3 Provence-Alpes-Côte d’Azur", "kind": "couverture médiatique"}, 
    {"source": "Philippe Chabeaudy", "target": "Data center Cézanne — Sybilles", "kind": "opposition locale"},
    {"source": "Lou Welgryn", "target": "Data for Good", "kind": "représentation"},
    {"source": "Maxime Colin", "target": "France Nature Environnement", "kind": "représentation"},
    {"source": "Maxime Efoui-Hess", "target": "Shift Project", "kind": "représentation"},
    {"source": "Michaël Reffay", "target": "France Datacenter", "kind": "représentation"},
    {"source": "France Datacenter", "target": "EDF", "kind": "soutien indirect"}
  ]
};
