const graphData = {
  "nodes": [
    {"id": "Campus IA Fouju", "label": "Campus IA\nFouju", "group": "Projet central", "size": 34, "detail": "Projet de méga-campus de centres de données et calcul IA à Fouju. Emprise de 90 hectares (130 terrains de football) sur terres agricoles. Consommation projetée à 1,4 GW (10,5 TWh), soit 2 % de la puissance électrique française ou 17 % de celle de l'Île-de-France."}, 
    
    /* OPPOSANTS NOMMÉS */
    {"id": "Jean-François Dupont", "label": "Jean-François\nDupont", "group": "Opposants nommés", "size": 17, "detail": "FNE 77. Opposant central : dénonce le caractère « hors norme » du projet, l'artificialisation accélérée, les risques de pollution PFAS et la procédure accélérée. Demande une prolongation de l'enquête publique."},
    {"id": "Jane Buisson", "label": "Jane\nBuisson", "group": "Opposants nommés", "size": 15, "detail": "Vice-présidente de FNE 77. A déposé une contribution officielle à l'enquête publique exigeant une nouvelle réunion publique et une rallonge des délais d'examen."},
    {"id": "Pauline Isambert", "label": "Pauline\nIsambert", "group": "Opposants nommés", "size": 17, "detail": "Confédération paysanne 77. Critique la perte de terres agricoles arables et conteste la souveraineté alimentaire ; souligne que 9 exploitations locales ont vendu leurs terres."},
    {"id": "Aline Aurias", "label": "Aline\nAurias", "group": "Opposants nommés", "size": 15, "detail": "Porte-parole de la Confédération paysanne. Opposée à la démesure et au flou entourant les consommations d'eau et le foncier. Critique une souveraineté financée par des capitaux étrangers."},
    {"id": "William Elie", "label": "William\nElie", "group": "Opposants nommés", "size": 16, "detail": "Alliance écologique et sociale. Exige un moratoire immédiat et cherche à politiser le dossier pour en faire un enjeu de débat national."},
    {"id": "Dorothée Villemaux", "label": "Dorothée\nVillemaux", "group": "Opposants nommés", "size": 15, "detail": "Les Écologistes de Melun Val de Seine. Alerte la population locale sur les impacts du projet qu'elle juge hautement problématique."},
    {"id": "Maxime Colin", "label": "Maxime\nColin", "group": "Opposants nommés", "size": 15, "detail": "FNE Île-de-France. Conteste l'argument de souveraineté numérique nationale et met en cause le financement par le fonds souverain des Émirats arabes unis."},
    {"id": "Lou Welgrym", "label": "Lou\nWelgrym", "group": "Opposants nommés", "size": 14, "detail": "Secrétaire générale de Data for Good. Critique la dérégulation administrative et la réduction systématique des capacités de recours juridiques des citoyens."},
    {"id": "Anne-Laure Ligozat", "label": "Anne-Laure\nLigozat", "group": "Opposants nommés", "size": 14, "detail": "Professeure au LISN. Déplore le manque de concertation publique et l'absence totale de grand débat national concernant la légitimité des usages du calcul."},
    {"id": "Marie Garin", "label": "Marie\nGarin", "group": "Opposants nommés", "size": 14, "detail": "Chercheuse postdoctorante au CNRS. Juge le dimensionnement de l'infrastructure déconnecté des besoins réels, reposant sur un pari spéculatif de marché."},
    {"id": "Marlène De Bank", "label": "Marlène\nDe Bank", "group": "Opposants nommés", "size": 14, "detail": "The Shift Project. Alerte sur la concurrence électrique et les risques majeurs d'arbitrages au détriment de pans entiers de la transition énergétique."},
    {"id": "Ophélie Coelho", "label": "Ophélie\nCoelho", "group": "Opposants nommés", "size": 14, "detail": "Chercheuse à l'IRIS. Spécialiste de la géopolitique du numérique, elle estime que les processus de concertation arrivent trop tardivement alors que 'la machine est déjà en route'."},
    {"id": "Irénée Régnauld", "label": "Irénée\nRégnauld", "group": "Opposants nommés", "size": 14, "detail": "Doctorant en sociologie. Critique le gigantisme matériel et la dépendance technologique qu'il induit, plaidant pour une planification publique."},
    {"id": "Olivier Petitjean", "label": "Olivier\nPetitjean", "group": "Opposants nommés", "size": 15, "detail": "Analyste à l'Observatoire des multinationales. Dénonce la soumission des politiques publiques aux intérêts financiers étrangers et de la Silicon Valley."},
    {"id": "Nadia Salhi", "label": "Nadia\nSalhi", "group": "Opposants nommés", "size": 15, "detail": "Déléguée syndicale CGT chez STMicroelectronics. Conteste le mirage des promesses d'emplois en s'appuyant sur les précédents industriels du directeur de projet."},
    {"id": "Laurence Allard", "label": "Laurence\nAllard", "group": "Opposants nommés", "size": 14, "detail": "Sociologue des usages du numérique. Observe et souligne la convergence citoyenne et l'appropriation transdisciplinaire exemplaire de la lutte de Fouju."},
    {"id": "Pauline Denis", "label": "Pauline\nDenis", "group": "Opposants nommés", "size": 15, "detail": "Ingénieure au Shift Project. S'indigne du découpage juridique du projet opéré selon elle pour contourner les réglementations et éviter un classement Seveso."},

    /* HABITANTS CITÉS */
    {"id": "Habitants Fernique", "label": "M. & Mme\nFernique", "group": "Habitants cités", "size": 15, "detail": "Habitants de Fouju. Dénoncent une infrastructure industrielle colossale imposée sans consultation préalable et s'interrogent : 'Est-ce qu’on a vraiment besoin de ce centre ?'"},
    {"id": "Christine Scialom", "label": "Christine\nScialom", "group": "Habitants cités", "size": 14, "detail": "Propriétaire foncière locale. Exprime un sentiment de déclassement territorial profond : 'On a l’impression d’être les poubelles de Paris'."},
    {"id": "Maud", "label": "Maud*\n(Maraîchère)", "group": "Habitants cités", "size": 14, "detail": "Maraîchère biologique installée près du site. Vivement inquiète des risques de pollution atmosphérique et de contamination des sols par les PFAS."},
    {"id": "Marie-Paule Direur", "label": "Marie-Paule\nDireur", "group": "Habitants cités", "size": 14, "detail": "Habitante mobilisée au Bourget (lutte SEGRO), incarnant la jonction de terrain entre les différentes contestations de centres de données en Île-de-France."},

    /* ÉLUS CRITIQUES */
    {"id": "Arnaud Saint-Martin", "label": "Arnaud\nSaint-Martin", "group": "Élus critiques", "size": 24, "detail": "Député LFI de Seine-et-Marne. Principal opposant politique au projet. Dénonce un projet inutile, énergivore et opaque porté par un 'courtier' ('Fouju devient une cause nationale')."},
    {"id": "Marianne Margaté", "label": "Marianne\nMargaté", "group": "Élus critiques", "size": 19, "detail": "Sénatrice communiste de Seine-et-Marne. S'oppose frontalement ; a déposé une question écrite fustigeant un contournement réglementaire par découpage artificiel du projet."},
    {"id": "Céline Malaisé", "label": "Céline\nMalaisé", "group": "Élus critiques", "size": 19, "detail": "Présidente du groupe de gauche à la Région IdF. Dénonce l'opacité totale du dossier à l'échelle régionale, le projet ayant été dissimulé derrière les plans d'une prison."},
    {"id": "Stéphanie Le Meur", "label": "Stéphanie\nLe Meur", "group": "Élus critiques", "size": 15, "detail": "Maire-adjointe socialiste de Moissy-Cramayel. Critique la contrainte financière qui étrangle les communes et les pousse indirectement à accepter le projet au niveau de l'agglomération."},
    {"id": "Jean-Luc Mélenchon", "label": "Jean-Luc\nMélenchon", "group": "Élus critiques", "size": 15, "detail": "Figure nationale LFI. Critique politique globale du modèle macro-économique, accusant l'exécutif de transformer la France en 'colonie numérique'."},
    {"id": "Députés socialistes", "label": "Députés\nsocialistes", "group": "Élus critiques", "size": 14, "detail": "Groupe socialiste à l'Assemblée nationale. Position d'encadrement critique législatif via le dépôt d'amendements contre la simplification administrative sans contreparties."},

    /* ÉLUS FAVORABLES / NUANCÉS */
    {"id": "Jonathan Wochenmayer", "label": "Jonathan\nWochenmayer", "group": "Élus favorables / nuancés", "size": 22, "detail": "Maire de Fouju. Très favorable au projet, il met en avant les retombées économiques et les recettes fiscales de sa commune. A interdit les rassemblements par arrêté municipal."},
    {"id": "Jean-Louis Thiériot", "label": "Jean-Louis\nThiériot", "group": "Élus favorables / nuancés", "size": 17, "detail": "Député LR de Seine-et-Marne. Soutient fermement l'infrastructure au nom de l'impératif de souveraineté technologique face aux blocs américain et chinois."},
    {"id": "Christian Poteau/Pointeau", "label": "Christian\nPoteau", "group": "Élus favorables / nuancés", "size": 16, "detail": "Président de la CC Brie des Rivières et Châteaux. Plutôt favorable ou rassuré, tout en se disant attentif aux impacts réels sur l'eau, la mobilité et l'économie locale."},
    {"id": "Hervé Jeannin", "label": "Hervé\nJeannin", "group": "Élus favorables / nuancés", "size": 16, "detail": "Maire de Crisenoy. Posture prudente et nuancée ; s'inquiète des hauteurs de bâtiments, de l'insertion paysagère, des risques d'inondations et du voisinage de la prison."},
    {"id": "Aymeric Durox", "label": "Aymeric\nDurox", "group": "Élus favorables / nuancés", "size": 15, "detail": "Sénateur RN de Seine-et-Marne. Favorable par pragmatisme compétitif territorial : considère qu'il vaut mieux implanter ces infrastructures en France qu'à l'étranger."},
    {"id": "Denis Larghero", "label": "Denis\nLarghero", "group": "Élus favorables / nuancés", "size": 14, "detail": "Maire UDI de Meudon, cité de manière générale pour sa défense des centres de données comme des leviers indispensables d'attractivité économique."},
    {"id": "Emmanuel Macron", "label": "Emmanuel\nMacron", "group": "Élus favorables / nuancés", "size": 18, "detail": "Président de la République. Totalement favorable au projet, promeut activement l'expansion à Choose France sous le slogan 'MGX choisit la France', ciblant 3 GW sur le territoire."},
    {"id": "Valérie Pécresse", "label": "Valérie\nPécresse", "group": "Élus favorables / nuancés", "size": 15, "detail": "Président de la Région Île-de-France. Posture ambiguë / non prononcée publiquement ; citée uniquement comme pouvoir décisionnaire final pour un éventuel cofinancement."},

    /* ORGANISATIONS LOCALES */
    {"id": "Stop Campus IA", "label": "Stop\nCampus IA", "group": "Organisations locales", "size": 24, "detail": "Collectif d'opposition locale, structurant la contestation citoyenne et les rassemblements militants sur le terrain à Fouju et Champeaux."},
    {"id": "FNE 77", "label": "FNE 77", "group": "Organisations locales", "size": 26, "detail": "Association environnementale départementale, pivot technique de la contestation (conférence de presse du 13 mai, dépôt de contributions)."},
    {"id": "FNE IDF", "label": "FNE\nÎle-de-France", "group": "Organisations locales", "size": 19, "detail": "Fédération régionale environnementale impliquée dans l'analyse juridique et la critique des implantations de centres de données en Île-de-France."},
    {"id": "Les Soulèvements de la Terre", "label": "Soulèvements\nde la Terre", "group": "Organisations locales", "size": 21, "detail": "Mouvement écologiste national, relais militant actif sur le terrain ayant mobilisé plus de 200 personnes lors des rassemblements du 24 mai."},
    {"id": "Confédération paysanne 77", "label": "Confédération\npaysanne 77", "group": "Organisations locales", "size": 22, "detail": "Syndicat agricole départemental fermement opposé au projet au nom de la défense des terres arables et de la souveraineté alimentaire face au bétonnage."},
    {"id": "Confédération paysanne IDF", "label": "Confédération\npaysanne IDF", "group": "Organisations locales", "size": 17, "detail": "Structure syndicale régionale mobilisée contre l'accaparement et la pression foncière exercée sur les ceintures maraîchères franciliennes."},
    {"id": "LPO 77", "label": "LPO 77", "group": "Organisations locales", "size": 18, "detail": "Association de protection de la biodiversité, membre de la coalition Stop Campus IA, proposant des inventaires naturalistes contradictoires du site."},
    {"id": "Écologistes Melun Val de Seine", "label": "Écologistes\nMelun Val", "group": "Organisations locales", "size": 17, "detail": "Structure politique écologiste locale représentée par Dorothée Villemaux."},
    {"id": "Solidaires", "label": "Solidaires", "group": "Organisations locales", "size": 18, "detail": "Union syndicale mobilisée au sein du collectif de contestation citoyenne et environnementale."},
    {"id": "Solidaires Informatique", "label": "Solidaires\nInformatique", "group": "Organisations locales", "size": 16, "detail": "Syndicat sectoriel présent lors des points presse pour apporter une expertise technique et sectorielle critique."},
    {"id": "Solidaires Essonne", "label": "Solidaires\nEssonne", "group": "Organisations locales", "size": 16, "detail": "Structure syndicale locale mobilisée (via l'intervention de William) en faveur d'un moratoire d'arrêt des constructions."},
    {"id": "Alliance écologique et sociale", "label": "Alliance\néco-sociale", "group": "Organisations locales", "size": 18, "detail": "Coalition syndicats-associations exigeant l'arrêt immédiat des simplifications administratives sans garanties."},
    {"id": "Attac", "label": "Attac", "group": "Organisations locales", "size": 15, "detail": "Association altermondialiste présente lors de la mobilisation transdisciplinaire citoyenne du 24 mai."},
    {"id": "Les Amis de la Terre", "label": "Amis de\nla Terre", "group": "Organisations locales", "size": 15, "detail": "Association environnementale nationale intégrée à la coalition de contestation publique contre Campus IA."},
    {"id": "Extinction Rebellion", "label": "Extinction\nRebellion", "group": "Organisations locales", "size": 15, "detail": "Collectif écologiste, engagé dans les actions directes et mobilisations de terrain à Champeaux."},

    /* PORTEURS ET PARTENAIRES ÉCONOMIQUES */
    {"id": "Thibaud Desfossés", "label": "Thibaud\nDesfossés", "group": "Porteurs / partenaires économiques", "size": 22, "detail": "Président de Campus IA / Directeur chez MGX. Invoque l'indépendance de calcul des entreprises mais se mure derrière le secret des affaires sur la gouvernance."},
    {"id": "MGX", "label": "MGX\n(Abou Dabi)", "group": "Porteurs / partenaires économiques", "size": 24, "detail": "Fonds d'investissement souverain des Émirats arabes unis, actionnaire majoritaire à 70 % du projet. Lié à l'appareil sécuritaire émirati."},
    {"id": "Bpifrance (BPI)", "label": "Bpifrance\n(BPI)", "group": "Porteurs / partenaires économiques", "size": 20, "detail": "Banque publique d'investissement française, actionnaire à 25 % assurant une présence de l'État dans la gouvernance (concède une souveraineté variable)."},
    {"id": "Eiffage / Eiffage Énergie Systèmes", "label": "Eiffage", "group": "Porteurs / partenaires économiques", "size": 19, "detail": "Groupe industriel attributaire officiel d'un marché industriel majeur de plus de 120 M€ pour la conception-réalisation de la sous-station haute tension."},
    {"id": "RTE", "label": "RTE", "group": "Porteurs / partenaires économiques", "size": 20, "detail": "Gestionnaire du réseau de transport d'électricité, signataire du contrat de raccordement électrique en amont de l'enquête publique."},
    {"id": "Nvidia", "label": "Nvidia", "group": "Porteurs / partenaires économiques", "size": 16, "detail": "Multinationale technologique actionnaire à 4 %, équipant le complexe de Fouju avec ses processeurs et composants de calcul."},

    /* RÉSEAU ÉLARGI ET CONTEXTES EXPERTS */
    {"id": "Printemps des luttes locales", "label": "Printemps des\nluttes locales", "group": "Réseau élargi", "size": 16, "detail": "Cadre militant et réseau de coordination ayant encadré le pique-nique protestataire contre Campus IA."},
    {"id": "Le Nuage était sous nos pieds", "label": "Le Nuage\nétait sous nos pieds", "group": "Réseau élargi", "size": 18, "detail": "Collectif marseillais techno-critique des centres de données, cité comme référence nationale de lutte d'appropriation technique."},
    {"id": "Collectif du Bourget", "label": "Collectif\ndu Bourget", "group": "Réseau élargi", "size": 15, "detail": "Collectif local opposé à un projet de centre de données Segro, établissant des passerelles de solidarité avec Fouju."},
    {"id": "Collectif de Vitry-sur-Seine", "label": "Collectif de\nVitry", "group": "Réseau élargi", "size": 15, "detail": "Collectif citoyen engagé dans la contestation francilienne globale contre la prolifération des infrastructures numériques."},
    {"id": "Collectif de Wissous", "label": "Collectif de\nWissous", "group": "Réseau élargi", "size": 15, "detail": "Collectif francilien engagé dans la contestation contre un projet distinct de l'opérateur CyrusOne."},
    {"id": "La Quadrature du Net", "label": "La Quadrature\ndu Net", "group": "Réseau élargi", "size": 18, "detail": "Association de défense des libertés numériques, réclamant un moratoire d'urbanisme sur les grands entrepôts de serveurs."},
    {"id": "Hiatus", "label": "Hiatus", "group": "Réseau élargi", "size": 15, "detail": "Collectif d'analyse techno-critique allié de La Quadrature du Net."},
    {"id": "STopMicro", "label": "STopMicro", "group": "Réseau élargi", "size": 14, "detail": "Collectif techno-critique grenoblois, cité comme référence de mobilisation contre les industries numériques de forte puissance."},
    {"id": "MRAe", "label": "MRAe (Autorité\nEnvironnementale)", "group": "Réseau élargi", "size": 18, "detail": "Mission Régionale d'Autorité Environnementale. Émet un avis d'alerte critique sur l'usage de gaz SF6 et les risques de fuites de PFAS."},
    {"id": "L’Européenne", "label": "L’Européenne", "group": "Réseau élargi", "size": 16, "detail": "Ancien porteur du projet logistique abandonné sur le site, bénéficiaire d'un protocole d'accord transactionnel avec la CC2SO."},
    {"id": "Commissaire-enquêteur", "label": "Commissaire-\nenquêteur", "group": "Réseau élargi", "size": 14, "detail": "Autorité indépendante ayant rendu un avis défavorable motivé sur l'ancien projet logistique au vu des nuisances de proximité."},

    /* MÉDIAS ET SOURCES D'INVESTIGATION */
    {"id": "Le Chiffon", "label": "Le Chiffon", "group": "Médias et sources", "size": 15, "detail": "Journal militant francilien ayant organisé des soirées-débats 'Contre les data centers et leur monde'."},
    {"id": "Actualité des luttes", "label": "Actualité\ndes luttes", "group": "Médias et sources", "size": 15, "detail": "Média militant indépendant assurant la couverture et le relais des mobilisations écologiques d'Île-de-France."},
    {"id": "mesinfos.fr", "label": "mesinfos.fr", "group": "Médias et sources", "size": 15, "detail": "Média d'information économique et légal ayant rendu publique l'attribution du marché de raccordement d'Eiffage."},
    {"id": "L’Humanité", "label": "L’Humanité", "group": "Médias et sources", "size": 16, "detail": "Quotidien national d'enquêtes (Pierric Marissal). Source ayant révélé le contrôle émirati (70% MGX) et les risques environnementaux."},
    {"id": "Observatoire des multinationales", "label": "Observatoire\nMultnationales", "group": "Médias et sources", "size": 16, "detail": "Plateforme d'investigation économique ayant démonté de manière critique les structures de capitaux cachées derrière Choose France."}
  ],
  "links": [
    {"source": "Campus IA Fouju", "target": "Jean-François Dupont", "kind": "position sur le projet"},
    {"source": "Campus IA Fouju", "target": "Jane Buisson", "kind": "position sur le projet"},
    {"source": "Campus IA Fouju", "target": "Pauline Isambert", "kind": "position sur le projet"},
    {"source": "Campus IA Fouju", "target": "Aline Aurias", "kind": "position sur le projet"},
    {"source": "Campus IA Fouju", "target": "William Elie", "kind": "position sur le projet"},
    {"source": "Campus IA Fouju", "target": "Dorothée Villemaux", "kind": "position sur le projet"},
    {"source": "Campus IA Fouju", "target": "Maxime Colin", "kind": "position sur le projet"},
    {"source": "Campus IA Fouju", "target": "Lou Welgrym", "kind": "position sur le projet"},
    {"source": "Campus IA Fouju", "target": "Anne-Laure Ligozat", "kind": "position sur le projet"},
    {"source": "Campus IA Fouju", "target": "Marie Garin", "kind": "position sur le projet"},
    {"source": "Campus IA Fouju", "target": "Marlène De Bank", "kind": "position sur le projet"},
    {"source": "Campus IA Fouju", "target": "Ophélie Coelho", "kind": "position sur le projet"},
    {"source": "Campus IA Fouju", "target": "Irénée Régnauld", "kind": "position sur le projet"},
    {"source": "Campus IA Fouju", "target": "Habitants Fernique", "kind": "position sur le projet"},
    {"source": "Campus IA Fouju", "target": "Christine Scialom", "kind": "position sur le projet"},
    {"source": "Campus IA Fouju", "target": "Maud", "kind": "position sur le projet"},
    {"source": "Campus IA Fouju", "target": "Arnaud Saint-Martin", "kind": "position sur le projet"},
    {"source": "Campus IA Fouju", "target": "Jean-Luc Mélenchon", "kind": "position sur le projet"},
    {"source": "Campus IA Fouju", "target": "Députés socialistes", "kind": "position sur le projet"},
    {"source": "Campus IA Fouju", "target": "Jonathan Wochenmayer", "kind": "position sur le projet"},
    {"source": "Campus IA Fouju", "target": "Jean-Louis Thiériot", "kind": "position sur le projet"},
    {"source": "Campus IA Fouju", "target": "Christian Poteau/Pointeau", "kind": "position sur le projet"},
    {"source": "Campus IA Fouju", "target": "Hervé Jeannin", "kind": "position sur le projet"},
    {"source": "Campus IA Fouju", "target": "Aymeric Durox", "kind": "position sur le projet"},
    {"source": "Campus IA Fouju", "target": "Denis Larghero", "kind": "position sur le projet"},
    {"source": "Campus IA Fouju", "target": "Stop Campus IA", "kind": "position sur le projet"},
    {"source": "Campus IA Fouju", "target": "FNE 77", "kind": "position sur le projet"},
    {"source": "Campus IA Fouju", "target": "FNE IDF", "kind": "position sur le projet"},
    {"source": "Campus IA Fouju", "target": "Les Soulèvements de la Terre", "kind": "position sur le projet"},
    {"source": "Campus IA Fouju", "target": "Confédération paysanne 77", "kind": "position sur le projet"},
    {"source": "Campus IA Fouju", "target": "Confédération paysanne IDF", "kind": "position sur le projet"},
    {"source": "Campus IA Fouju", "target": "LPO 77", "kind": "position sur le projet"},
    {"source": "Campus IA Fouju", "target": "Écologistes Melun Val de Seine", "kind": "position sur le projet"},
    {"source": "Campus IA Fouju", "target": "Solidaires", "kind": "position sur le projet"},
    {"source": "Campus IA Fouju", "target": "Solidaires Informatique", "kind": "position sur le projet"},
    {"source": "Campus IA Fouju", "target": "Solidaires Essonne", "kind": "position sur le projet"},
    {"source": "Campus IA Fouju", "target": "Alliance écologique et sociale", "kind": "position sur le projet"},

    /* Nouveaux liens du rapport de veille du 22 juin 2026 */
    {"source": "Campus IA Fouju", "target": "MGX", "kind": "lien structurel"},
    {"source": "Campus IA Fouju", "target": "Bpifrance (BPI)", "kind": "lien structurel"},
    {"source": "Campus IA Fouju", "target": "Eiffage / Eiffage Énergie Systèmes", "kind": "lien structurel"},
    {"source": "Campus IA Fouju", "target": "RTE", "kind": "lien structurel"},
    {"source": "Campus IA Fouju", "target": "Nvidia", "kind": "lien structurel"},
    {"source": "Campus IA Fouju", "target": "Emmanuel Macron", "kind": "appui étatique"},
    {"source": "Campus IA Fouju", "target": "Valérie Pécresse", "kind": "pouvoir régional"},
    {"source": "Campus IA Fouju", "target": "Marianne Margaté", "kind": "contestation parlementaire"},
    {"source": "Campus IA Fouju", "target": "Céline Malaisé", "kind": "contestation régionale"},
    {"source": "Campus IA Fouju", "target": "MRAe", "kind": "évaluation environnementale"},
    {"source": "Campus IA Fouju", "target": "L’Européenne", "kind": "litige foncier"},
    {"source": "Campus IA Fouju", "target": "Olivier Petitjean", "kind": "analyse critique"},
    {"source": "Campus IA Fouju", "target": "Nadia Salhi", "kind": "alerte emploi"},
    {"source": "Campus IA Fouju", "target": "Laurence Allard", "kind": "analyse sociologique"},
    {"source": "Campus IA Fouju", "target": "Pauline Denis", "kind": "alerte technique"},
    {"source": "Campus IA Fouju", "target": "Attac", "kind": "coalition élargie"},
    {"source": "Campus IA Fouju", "target": "Les Amis de la Terre", "kind": "coalition élargie"},
    {"source": "Campus IA Fouju", "target": "Extinction Rebellion", "kind": "coalition élargie"},

    /* Rattachements d'expertises et de structures de la coalition */
    {"source": "Jean-François Dupont", "target": "FNE 77", "kind": "rattachement"},
    {"source": "Jane Buisson", "target": "FNE 77", "kind": "rattachement"},
    {"source": "Pauline Isambert", "target": "Confédération paysanne 77", "kind": "rattachement"},
    {"source": "Aline Aurias", "target": "Confédération paysanne IDF", "kind": "rattachement"},
    {"source": "William Elie", "target": "Alliance écologique et sociale", "kind": "rattachement"},
    {"source": "Dorothée Villemaux", "target": "Écologistes Melun Val de Seine", "kind": "rattachement"},
    {"source": "Maxime Colin", "target": "FNE IDF", "kind": "rattachement"},
    {"source": "Lou Welgrym", "target": "La Quadrature du Net", "kind": "réseau expert"},
    {"source": "Marlène De Bank", "target": "The Shift Project", "kind": "rattachement"},
    {"source": "Pauline Denis", "target": "The Shift Project", "kind": "rattachement"},
    {"source": "Olivier Petitjean", "target": "Observatoire des multinationales", "kind": "rattachement"},
    {"source": "Nadia Salhi", "target": "L’Humanité", "kind": "source tribune"},

    /* Maillages et coordinations d'acteurs */
    {"source": "Stop Campus IA", "target": "FNE 77", "kind": "coordination locale"},
    {"source": "Stop Campus IA", "target": "Confédération paysanne 77", "kind": "coordination locale"},
    {"source": "Stop Campus IA", "target": "Les Soulèvements de la Terre", "kind": "coordination locale"},
    {"source": "Stop Campus IA", "target": "LPO 77", "kind": "coordination locale"},
    {"source": "Attac", "target": "Les Amis de la Terre", "kind": "front commun"},
    {"source": "Extinction Rebellion", "target": "Les Soulèvements de la Terre", "kind": "front commun"},
    {"source": "Thibaud Desfossés", "target": "MGX", "kind": "direction"},
    {"source": "MGX", "target": "Emmanuel Macron", "kind": "Choose France"},
    {"source": "Eiffage / Eiffage Énergie Systèmes", "target": "RTE", "kind": "raccordement contractuel"},
    {"source": "Marianne Margaté", "target": "Céline Malaisé", "kind": "bloc gauche"},
    {"source": "Stéphanie Le Meur", "target": "Céline Malaisé", "kind": "bloc gauche"},
    {"source": "L’Européenne", "target": "Commissaire-enquêteur", "kind": "passé administratif"},

    /* Ancrages Fonciers des Habitants */
    {"source": "Habitants Fernique", "target": "Stop Campus IA", "kind": "riverains"},
    {"source": "Christine Scialom", "target": "Stop Campus IA", "kind": "riverains"},
    {"source": "Maud", "target": "Confédération paysanne 77", "kind": "maraîchage impacté"},

    /* Couvertures médiatiques et sources réglementaires du corpus */
    {"source": "Campus IA Fouju", "target": "L’Humanité", "kind": "source"},
    {"source": "Eiffage / Eiffage Énergie Systèmes", "target": "mesinfos.fr", "kind": "source"},
    {"source": "MGX", "target": "Observatoire des multinationales", "kind": "source"},
    {"source": "Stop Campus IA", "target": "Le Monde / Le Chiffon / Actualité des luttes", "kind": "source"}
  ]
};
