const graphData = {
  "nodes": [
    {"id": "Campus IA Fouju", "label": "Campus IA\nFouju", "group": "Projet central", "size": 34, "detail": "Projet de méga-campus IA / data centers à Fouju, autour duquel se structurent les oppositions, soutiens et positions nuancées."}, 
    {"id": "Jean-François Dupont", "label": "Jean-François\nDupont", "group": "Opposants nommés", "size": 20, "detail": "FNE 77. Opposant central : critique le caractère « hors norme », les PFAS, l'artificialisation, la consommation énergétique et la procédure accélérée."}, 
    {"id": "Jane Buisson", "label": "Jane\nBuisson", "group": "Opposants nommés", "size": 16, "detail": "Vice-présidente de FNE 77. Associée à la remise d’une contribution à l’enquête publique et à la demande d’allongement de l’enquête."}, 
    {"id": "Pauline Isambert", "label": "Pauline\nIsambert", "group": "Opposants nommés", "size": 20, "detail": "Confédération paysanne 77. Critique la perte de terres agricoles, les risques sur l’eau et les PFAS ; rappelle que neuf exploitations ont vendu leurs terres."}, 
    {"id": "Aline Aurias", "label": "Aline\nAurias", "group": "Opposants nommés", "size": 17, "detail": "Porte-parole de la Confédération paysanne. Dénonce l’artificialisation, la pression foncière et le flou sur l’eau."}, 
    {"id": "William Elie", "label": "William\nElie", "group": "Opposants nommés", "size": 18, "detail": "Alliance écologique et sociale. Appelle à un moratoire et souhaite faire des data centers un sujet de débat national."}, 
    {"id": "Dorothée Villemaux", "label": "Dorothée\nVillemaux", "group": "Opposants nommés", "size": 16, "detail": "Les Écologistes de Melun Val de Seine. Appelle la population à consulter le dossier et à participer à l’enquête publique."}, 
    {"id": "Maxime Colin", "label": "Maxime\nColin", "group": "Opposants nommés", "size": 16, "detail": "FNE Île-de-France. Critique la vague rapide de projets de data centers et l’argument de souveraineté, notamment à cause du financement émirati."}, 
    {"id": "Lou Welgrym", "label": "Lou\nWelgrym", "group": "Opposants nommés", "size": 15, "detail": "Data for Good. Critique la dérégulation et la réduction des capacités de recours des citoyens."}, 
    {"id": "Pop", "label": "« Pop »", "group": "Opposants nommés", "size": 14, "detail": "Membre anonyme du collectif Le Nuage était sous nos pieds. Témoigne de la difficulté à s’opposer au discours des promoteurs."}, 
    {"id": "Marie-Paule Direur", "label": "Marie-Paule\nDireur", "group": "Opposants nommés", "size": 14, "detail": "Habitante mobilisée au Bourget contre un projet Segro ; citée dans la contestation plus large des data centers."}, 
    {"id": "Anne-Laure Ligozat", "label": "Anne-Laure\nLigozat", "group": "Opposants nommés", "size": 15, "detail": "Professeure en informatique. Critique l’absence de débat national sur les data centers."}, 
    {"id": "Marie Garin", "label": "Marie\nGarin", "group": "Opposants nommés", "size": 15, "detail": "Postdoctorante au CNRS. Estime que la planification massive repose sur un pari d’usage futur plutôt que sur un besoin concret établi."}, 
    {"id": "Marlène De Bank", "label": "Marlène\nDe Bank", "group": "Opposants nommés", "size": 14, "detail": "The Shift Project. Alerte sur les risques de conflits d’usage électriques."}, 
    {"id": "Ophélie Coelho", "label": "Ophélie\nCoelho", "group": "Opposants nommés", "size": 14, "detail": "Chercheuse à l’IRIS. Critique un débat public intervenant après l’engagement des grandes décisions."}, 
    {"id": "Irénée Régnauld", "label": "Irénée\nRégnauld", "group": "Opposants nommés", "size": 14, "detail": "Doctorant en sociologie. Critique le gigantisme numérique, la dépendance technologique et une souveraineté numérique jugée illusoire."}, 
    {"id": "Habitants Fernique", "label": "M. & Mme\nFernique", "group": "Habitants cités", "size": 15, "detail": "Habitants de Fouju. Critiquent la manière dont le projet a été découvert localement et interrogent son utilité réelle."}, 
    {"id": "Christine Scialom", "label": "Christine\nScialom", "group": "Habitants cités", "size": 14, "detail": "Habitante / propriétaire concernée. Exprime un sentiment de déclassement territorial : « les poubelles de Paris »."}, 
    {"id": "Maud", "label": "Maud*", "group": "Habitants cités", "size": 14, "detail": "Maraîchère bio près du site. Inquiète des pollutions atmosphériques et des PFAS."}, 
    {"id": "Arnaud Saint-Martin", "label": "Arnaud\nSaint-Martin", "group": "Élus critiques", "size": 24, "detail": "Député LFI de Seine-et-Marne. Principal élu opposé : critique un projet imposé, énergivore, artificialisant et dépendant d’acteurs étrangers."}, 
    {"id": "Jean-Luc Mélenchon", "label": "Jean-Luc\nMélenchon", "group": "Élus critiques", "size": 15, "detail": "Cité dans le débat général ; critique le risque de « colonie numérique »."}, 
    {"id": "Députés socialistes", "label": "Députés\nsocialistes", "group": "Élus critiques", "size": 14, "detail": "Mentionnés pour des amendements d’encadrement des simplifications applicables aux data centers."}, 
    {"id": "Jonathan Wochenmayer", "label": "Jonathan\nWochenmayer", "group": "Élus favorables / nuancés", "size": 22, "detail": "Maire de Fouju. Très favorable : met en avant les retombées économiques, les emplois, la taxe foncière et les recettes communales."}, 
    {"id": "Jean-Louis Thiériot", "label": "Jean-Louis\nThiériot", "group": "Élus favorables / nuancés", "size": 17, "detail": "Député LR de Seine-et-Marne. Favorable aux data centers au nom de la souveraineté technologique."}, 
    {"id": "Christian Poteau/Pointeau", "label": "Christian\nPoteau /\nPointeau", "group": "Élus favorables / nuancés", "size": 16, "detail": "Président de la Communauté de communes Brie des Rivières et Châteaux. Plutôt favorable ou rassuré, attentif à l’eau, la mobilité et aux retombées locales."}, 
    {"id": "Hervé Jeannin", "label": "Hervé\nJeannin", "group": "Élus favorables / nuancés", "size": 16, "detail": "Maire de Crisenoy. Position nuancée : relaie des inquiétudes sur les inondations, le paysage, la hauteur des bâtiments et la coordination avec la prison."}, 
    {"id": "Aymeric Durox", "label": "Aymeric\nDurox", "group": "Élus favorables / nuancés", "size": 15, "detail": "Sénateur RN de Seine-et-Marne. Plutôt favorable/pragmatique : mieux vaut que le projet se fasse en France qu’ailleurs."}, 
    {"id": "Denis Larghero", "label": "Denis\nLarghero", "group": "Élus favorables / nuancés", "size": 14, "detail": "Maire UDI de Meudon. Cité dans un passage général ; favorable aux infrastructures numériques comme levier d’attractivité."}, 
    {"id": "Stop Campus IA", "label": "Stop\nCampus IA", "group": "Organisations locales", "size": 24, "detail": "Collectif directement structuré contre le projet de Fouju."}, 
    {"id": "FNE 77", "label": "FNE 77", "group": "Organisations locales", "size": 26, "detail": "Acteur central de l’opposition locale : contribution à l’enquête publique, conférence de presse, critique environnementale."}, 
    {"id": "FNE IDF", "label": "FNE\nÎle-de-France", "group": "Organisations locales", "size": 19, "detail": "Fédération régionale impliquée dans la critique des data centers en Île-de-France."}, 
    {"id": "Les Soulèvements de la Terre", "label": "Soulèvements\nde la Terre", "group": "Organisations locales", "size": 21, "detail": "Mouvement écologiste mobilisé contre Campus IA ; relaie la mobilisation."}, 
    {"id": "Confédération paysanne 77", "label": "Confédération\npaysanne 77", "group": "Organisations locales", "size": 22, "detail": "Syndicat agricole opposé pour artificialisation, souveraineté alimentaire, eau et foncier."}, 
    {"id": "Confédération paysanne IDF", "label": "Confédération\npaysanne IDF", "group": "Organisations locales", "size": 17, "detail": "Organisation régionale mobilisée contre l’artificialisation agricole."}, 
    {"id": "LPO 77", "label": "LPO 77", "group": "Organisations locales", "size": 18, "detail": "Association environnementale citée parmi les organisations mobilisées."}, 
    {"id": "Écologistes Melun Val de Seine", "label": "Écologistes\nMelun Val\nde Seine", "group": "Organisations locales", "size": 17, "detail": "Organisation écologiste locale représentée par Dorothée Villemaux."}, 
    {"id": "Solidaires", "label": "Solidaires", "group": "Organisations locales", "size": 18, "detail": "Syndicat cité parmi les organisations mobilisées."}, 
    {"id": "Solidaires Informatique", "label": "Solidaires\nInformatique", "group": "Organisations locales", "size": 16, "detail": "Syndicat présent dans la conférence de presse du 13 mai."}, 
    {"id": "Solidaires Essonne", "label": "Solidaires\nde l’Essonne", "group": "Organisations locales", "size": 16, "detail": "Syndicat cité via l’intervention de William."}, 
    {"id": "Alliance écologique et sociale", "label": "Alliance\nécologique\net sociale", "group": "Organisations locales", "size": 18, "detail": "Coalition syndicats-associations appelant à un moratoire."}, 
    {"id": "Printemps des luttes locales", "label": "Printemps\ndes luttes\nlocales", "group": "Réseau élargi", "size": 16, "detail": "Cadre militant du pique-nique contre Campus IA."}, 
    {"id": "Le Nuage était sous nos pieds", "label": "Le Nuage\nétait sous\nnos pieds", "group": "Réseau élargi", "size": 18, "detail": "Collectif marseillais critique des data centers, cité comme référence nationale."}, 
    {"id": "Collectif du Bourget", "label": "Collectif\ndu Bourget", "group": "Réseau élargi", "size": 15, "detail": "Collectif local opposé à un projet de data center au Bourget."}, 
    {"id": "Collectif de Vitry-sur-Seine", "label": "Collectif de\nVitry-sur-Seine", "group": "Réseau élargi", "size": 15, "detail": "Collectif cité dans la mobilisation francilienne contre les data centers."}, 
    {"id": "Collectif de Wissous", "label": "Collectif de\nWissous", "group": "Réseau élargi", "size": 15, "detail": "Collectif cité dans la contestation contre un projet CyrusOne."}, 
    {"id": "La Quadrature du Net", "label": "La Quadrature\ndu Net", "group": "Réseau élargi", "size": 18, "detail": "Association critique du numérique, favorable à un moratoire sur les grands entrepôts de serveurs."}, 
    {"id": "Hiatus", "label": "Hiatus", "group": "Réseau élargi", "size": 15, "detail": "Collectif critique du numérique cité avec La Quadrature du Net et Le Nuage était sous nos pieds."}, 
    {"id": "Data for Good", "label": "Data for\nGood", "group": "Réseau élargi", "size": 16, "detail": "Association représentée par Lou Welgrym, critique de la dérégulation et des limitations de recours."}, 
    {"id": "The Shift Project", "label": "The Shift\nProject", "group": "Réseau élargi", "size": 16, "detail": "Think tank alertant sur les risques énergétiques et les conflits d’usage."}, 
    {"id": "X-alternative", "label": "X-alternative", "group": "Réseau élargi", "size": 14, "detail": "Association mentionnée dans le cadre de contre-expertises sur l’IA."}, 
    {"id": "STopMicro", "label": "STopMicro", "group": "Réseau élargi", "size": 14, "detail": "Collectif techno-critique cité comme référence de mobilisation contre les industries numériques."}, 
    {"id": "Le Chiffon", "label": "Le Chiffon", "group": "Médias militants", "size": 15, "detail": "Journal militant ayant organisé une soirée-débat « Contre les data centers et leur monde »."}, 
    {"id": "Actualité des luttes", "label": "Actualité\ndes luttes", "group": "Médias militants", "size": 15, "detail": "Média militant relayant les mobilisations contre les data centers en Île-de-France."}
  ], 
  "links": [
    {"source": "Campus IA Fouju", "target": "Jean-François Dupont", "kind": "position sur le projet"}, 
    {"source": "Campus IA Fouju", "target": "Jane Buisson", "kind": "position sur le projet"}, 
    {"source": "Campus IA Fouju", "target": "Pauline Isambert", "kind": "position sur le projet"}, 
    {"source": "Campus IA Fouju", "target": "Aline Aurias", "kind": "position sur le projet"}, 
    {"source": "Campus IA Fouju", "target": "William Elie", "kind": "position sur le projet"}, 
    {"source": "Campus IA Fouju", "target": "Dorothée Villemaux", "kind": "position sur le projet"}, 
    {"source": "Campus IA Fouju", "target": "Maxime Colin", "kind": "position sur le projet"}, 
    {"source": "Campus IA Fouju", "target": "Lou Welgrym", "kind": "position sur le projet"}, 
    {"source": "Campus IA Fouju", "target": "Pop", "kind": "position sur le projet"}, 
    {"source": "Campus IA Fouju", "target": "Marie-Paule Direur", "kind": "position sur le projet"}, 
    {"source": "Campus IA Fouju", "target": "Anne-Laure Ligozat", "kind": "position sur le projet"}, 
    {"source": "Campus IA Fouju", "target": "Marie Garin", "kind": "position sur le projet"}, 
    {"source": "Campus IA Fouju", "target": "Marlène De Bank", "kind": "position sur le projet"}, 
    {"source": "Campus IA Fouju", "target": "Ophélie Coelho", "kind": "position sur le projet"}, 
    {"source": "Campus IA Fouju", "target": "Irénée Régnauld", "kind": "position sur le projet"}, 
    {"source": "Campus IA Fouju", "target": "Habitants Fernique", "kind": "position sur le projet"}, 
    {"source": "Campus IA Fouju", "target": "Christine Scialom", "kind": "position sur le projet"}, 
    {"source": "Campus IA Fouju", "target": "Maud", "kind": "position sur le projet"}, 
    {"source": "Campus IA Fouju", "target": "Arnaud Saint-Martin", "kind": "position sur le projet"}, 
    {"source": "Campus IA Fouju", "target": "Jean-Luc Mélenchon", "kind": "position sur le projet"}, 
    {"source": "Campus IA Fouju", "target": "Députés socialistes", "kind": "position sur le projet"}, 
    {"source": "Campus IA Fouju", "target": "Jonathan Wochenmayer", "kind": "position sur le projet"}, 
    {"source": "Campus IA Fouju", "target": "Jean-Louis Thiériot", "kind": "position sur le projet"}, 
    {"source": "Campus IA Fouju", "target": "Christian Poteau/Pointeau", "kind": "position sur le projet"}, 
    {"source": "Campus IA Fouju", "target": "Hervé Jeannin", "kind": "position sur le projet"}, 
    {"source": "Campus IA Fouju", "target": "Aymeric Durox", "kind": "position sur le projet"}, 
    {"source": "Campus IA Fouju", "target": "Denis Larghero", "kind": "position sur le projet"}, 
    {"source": "Campus IA Fouju", "target": "Stop Campus IA", "kind": "position sur le projet"}, 
    {"source": "Campus IA Fouju", "target": "FNE 77", "kind": "position sur le projet"}, 
    {"source": "Campus IA Fouju", "target": "FNE IDF", "kind": "position sur le projet"}, 
    {"source": "Campus IA Fouju", "target": "Les Soulèvements de la Terre", "kind": "position sur le projet"}, 
    {"source": "Campus IA Fouju", "target": "Confédération paysanne 77", "kind": "position sur le projet"}, 
    {"source": "Campus IA Fouju", "target": "Confédération paysanne IDF", "kind": "position sur le projet"}, 
    {"source": "Campus IA Fouju", "target": "LPO 77", "kind": "position sur le projet"}, 
    {"source": "Campus IA Fouju", "target": "Écologistes Melun Val de Seine", "kind": "position sur le projet"}, 
    {"source": "Campus IA Fouju", "target": "Solidaires", "kind": "position sur le projet"}, 
    {"source": "Campus IA Fouju", "target": "Solidaires Informatique", "kind": "position sur le projet"}, 
    {"source": "Campus IA Fouju", "target": "Solidaires Essonne", "kind": "position sur le projet"}, 
    {"source": "Campus IA Fouju", "target": "Alliance écologique et sociale", "kind": "position sur le projet"}, 
    {"source": "Jean-François Dupont", "target": "FNE 77", "kind": "rattachement / proximité"}, 
    {"source": "Jane Buisson", "target": "FNE 77", "kind": "rattachement / proximité"}, 
    {"source": "Pauline Isambert", "target": "Confédération paysanne 77", "kind": "rattachement / proximité"}, 
    {"source": "Aline Aurias", "target": "Confédération paysanne IDF", "kind": "rattachement / proximité"}, 
    {"source": "William Elie", "target": "Alliance écologique et sociale", "kind": "rattachement / proximité"}, 
    {"source": "William Elie", "target": "Solidaires Essonne", "kind": "rattachement / proximité"}, 
    {"source": "Dorothée Villemaux", "target": "Écologistes Melun Val de Seine", "kind": "rattachement / proximité"}, 
    {"source": "Maxime Colin", "target": "FNE IDF", "kind": "rattachement / proximité"}, 
    {"source": "Lou Welgrym", "target": "Data for Good", "kind": "rattachement / proximité"}, 
    {"source": "Pop", "target": "Le Nuage était sous nos pieds", "kind": "rattachement / proximité"}, 
    {"source": "Marie-Paule Direur", "target": "Collectif du Bourget", "kind": "rattachement / proximité"}, 
    {"source": "Marlène De Bank", "target": "The Shift Project", "kind": "rattachement / proximité"}, 
    {"source": "Arnaud Saint-Martin", "target": "Stop Campus IA", "kind": "rattachement / proximité"}, 
    {"source": "Stop Campus IA", "target": "FNE 77", "kind": "coalition locale"}, 
    {"source": "Stop Campus IA", "target": "FNE IDF", "kind": "coalition locale"}, 
    {"source": "Stop Campus IA", "target": "Les Soulèvements de la Terre", "kind": "coalition locale"}, 
    {"source": "Stop Campus IA", "target": "Confédération paysanne 77", "kind": "coalition locale"}, 
    {"source": "Stop Campus IA", "target": "Confédération paysanne IDF", "kind": "coalition locale"}, 
    {"source": "Stop Campus IA", "target": "LPO 77", "kind": "coalition locale"}, 
    {"source": "Stop Campus IA", "target": "Écologistes Melun Val de Seine", "kind": "coalition locale"}, 
    {"source": "Stop Campus IA", "target": "Solidaires", "kind": "coalition locale"}, 
    {"source": "Stop Campus IA", "target": "Solidaires Informatique", "kind": "coalition locale"}, 
    {"source": "Stop Campus IA", "target": "Alliance écologique et sociale", "kind": "coalition locale"}, 
    {"source": "Campus IA Fouju", "target": "Collectif du Bourget", "kind": "réseau élargi / contexte data centers"}, 
    {"source": "Campus IA Fouju", "target": "Collectif de Vitry-sur-Seine", "kind": "réseau élargi / contexte data centers"}, 
    {"source": "Campus IA Fouju", "target": "Collectif de Wissous", "kind": "réseau élargi / contexte data centers"}, 
    {"source": "Campus IA Fouju", "target": "La Quadrature du Net", "kind": "réseau élargi / contexte data centers"}, 
    {"source": "Campus IA Fouju", "target": "Hiatus", "kind": "réseau élargi / contexte data centers"}, 
    {"source": "Campus IA Fouju", "target": "Le Nuage était sous nos pieds", "kind": "réseau élargi / contexte data centers"}, 
    {"source": "Campus IA Fouju", "target": "Data for Good", "kind": "réseau élargi / contexte data centers"}, 
    {"source": "Campus IA Fouju", "target": "The Shift Project", "kind": "réseau élargi / contexte data centers"}, 
    {"source": "Campus IA Fouju", "target": "X-alternative", "kind": "réseau élargi / contexte data centers"}, 
    {"source": "Campus IA Fouju", "target": "STopMicro", "kind": "réseau élargi / contexte data centers"}, 
    {"source": "Campus IA Fouju", "target": "Le Chiffon", "kind": "réseau élargi / contexte data centers"}, 
    {"source": "Campus IA Fouju", "target": "Actualité des luttes", "kind": "réseau élargi / contexte data centers"}
  ]
};
