const graphData = {
  "nodes": [
    {"id": "Campus numérique et industriel du Bosquel", "label": "Campus numérique et industriel du Bosquel", "group": "Projet central", "size": 28, "detail": "Projet de supercalculateur / campus IA sur la ZAC du Bosquel, site Fast Track RTE, avec une capacité pré-réservée de 1 GW."}, 
    {"id": "ZAC du Bosquel", "label": "ZAC du Bosquel", "group": "Projet central", "size": 22, "detail": "Site de 46 hectares, dont 33 hectares dédiés au futur opérateur et 13 hectares vendus à RTE pour le raccordement."}, 
    {"id": "Silver Bands France Computer Center Bosquel", "label": "Silver Bands France Computer\nCenter Bosquel", "group": "Porteur / lauréat industriel", "size": 22, "detail": "Lauréat de l’AMI choisi par les élus de la CC2SO pour construire puis exploiter le supercalculateur. Lié au management de SoftBank."}, 
    {"id": "Société spécifique au Bosquel", "label": "Société spécifique au Bosquel", "group": "Porteur / lauréat industriel", "size": 15, "detail": "Entité annoncée comme devant être créée avec siège au Bosquel et obligation de travailler avec les étudiants amiénois."}, 
    {"id": "Fluidstack", "label": "Fluidstack", "group": "Porteur / lauréat industriel", "size": 22, "detail": "Ancien projet pressenti, finalement abandonné au profit d’une réorientation vers les États-Unis selon plusieurs articles."}, 
    {"id": "CC2SO", "label": "CC2SO", "group": "Institutions territoriales", "size": 22, "detail": "Communauté de communes Somme Sud-Ouest ; pilote territorial de l’AMI et propriétaire des terrains via un bail de 99 ans."}, 
    {"id": "Alain Desfosses", "label": "Alain Desfosses", "group": "Institutions territoriales", "size": 22, "detail": "Président de la CC2SO ; défend le projet, rappelle l’urgence de choisir un opérateur avant l’échéance Fast Track et promet une présentation aux riverains."}, 
    {"id": "Laurent Snoeck", "label": "Laurent Snoeck", "group": "Institutions territoriales", "size": 18, "detail": "Directeur général des services ; répond aux inquiétudes sur l’eau en évoquant un circuit fermé et une consommation de 265 m³/an."}, 
    {"id": "Arnaud De Monclin", "label": "Arnaud De Monclin", "group": "Institutions territoriales", "size": 18, "detail": "Maire de Courcelles-sous-Thoix ; exprime une inquiétude légitime sur les besoins en eau et demande une étude indépendante sur la nappe phréatique."}, 
    {"id": "Maison des Jeunes d’Hornoy-le-Bourg", "label": "Maison des Jeunes d’Hornoy-le-Bourg", "group": "Institutions territoriales", "size": 15, "detail": "Lieu de la réunion communautaire durant laquelle le choix du lauréat de l’AMI est présenté."}, 
    {"id": "État", "label": "État", "group": "État / acteurs publics nationaux", "size": 22, "detail": "Demande à RTE de pré-réserver une capacité de 1 GW sur le site du Bosquel ; inscrit le site dans la logique Fast Track."}, 
    {"id": "Bercy", "label": "Bercy", "group": "État / acteurs publics nationaux", "size": 15, "detail": "Le ministère suit de près la sécurisation des investissements IA et la sélection des sites stratégiques de centres de données."}, 
    {"id": "Anne Le Hénanff", "label": "Anne Le Hénanff", "group": "État / acteurs publics nationaux", "size": 15, "detail": "Ministre déléguée chargée de l’IA et du Numérique ; associée aux Rencontres des centres de données et au suivi des sites sécurisés."}, 
    {"id": "François Bayrou", "label": "François Bayrou", "group": "État / acteurs publics nationaux", "size": 15, "detail": "Cité comme Premier ministre ayant annoncé une liste de sites industriels clés en main dédiés aux data centers."}, 
    {"id": "Emmanuel Macron", "label": "Emmanuel Macron", "group": "État / acteurs publics nationaux", "size": 15, "detail": "Porteur politique du plan IA. A directement rencontré Masayoshi Son (SoftBank) dans le cadre de la relance du projet du Bosquel."}, 
    {"id": "CRE", "label": "CRE", "group": "État / acteurs publics nationaux", "size": 15, "detail": "A approuvé la procédure spécifique de raccordement rapide pour installations de très forte puissance."}, 
    {"id": "DGE", "label": "DGE", "group": "État / acteurs publics nationaux", "size": 15, "detail": "Direction générale des entreprises ; citée dans l’accompagnement des porteurs de projets via la Task Force de l’État."}, 
    {"id": "Business France", "label": "Business France", "group": "État / acteurs publics nationaux", "size": 15, "detail": "Membre de la Task Force de l’État accompagnant les entreprises de data centers."}, 
    {"id": "RTE", "label": "RTE", "group": "Énergie / raccordement", "size": 22, "detail": "Gestionnaire du réseau ; pré-réservation de capacité, procédure Fast Track, raccordement prioritaire et réflexion sur l’allocation dynamique des capacités."}, 
    {"id": "Nathalie Lemaître", "label": "Nathalie Lemaître", "group": "Énergie / raccordement", "size": 18, "detail": "Directrice générale du pôle Clients Systèmes Innovation chez RTE ; alerte sur les capacités réservées et la nécessité de servir les projets les plus crédibles."}, 
    {"id": "EDF", "label": "EDF", "group": "Énergie / raccordement", "size": 15, "detail": "Cité avec l’État bit-RTE comme acteur proposant ou identifiant des sites d’implantation possibles en Picardie."}, 
    {"id": "Lignes haute tension", "label": "Lignes haute tension", "group": "Énergie / raccordement", "size": 15, "detail": "Deux lignes haute tension traversent ou alimentent le site, constituant un facteur d’attractivité pour un projet très consommateur d’électricité."}, 
    {"id": "Étudiants amiénois", "label": "Étudiants amiénois", "group": "Recherche / formation / écosystème IA", "size": 15, "detail": "Le futur opérateur doit travailler avec les étudiants amiénois, selon les obligations évoquées par la CC2SO."}, 
    {"id": "Entreprises et start-up utilisatrices", "label": "Entreprises et start-up utilisatrices", "group": "Recherche / formation / écosystème IA", "size": 15, "detail": "Des espaces doivent être dédiés aux entreprises et start-up souhaitant utiliser la puissance du supercalculateur."}, 
    {"id": "Mistral AI", "label": "Mistral AI", "group": "Recherche / formation / écosystème IA", "size": 15, "detail": "Cité comme symbole des besoins en calcul souverain ; fait l'objet d'un différend commercial distinct avec Sesterce."}, 
    {"id": "Eclairion", "label": "Eclairion", "group": "Recherche / formation / écosystème IA", "size": 15, "detail": "Cité dans le contexte du retrait de Fluidstack sur un projet en région parisienne avec Mistral."}, 
    {"id": "Anthropic", "label": "Anthropic", "group": "Recherche / formation / écosystème IA", "size": 15, "detail": "Client américain de Fluidstack dans le cadre d’un contrat massif aux États-Unis, contribuant à la réorientation de Fluidstack."}, 
    {"id": "Google", "label": "Google", "group": "Recherche / formation / écosystème IA", "size": 15, "detail": "Cité comme investisseur potentiel dans Fluidstack, renforçant l’attraction américaine."}, 
    {"id": "Nvidia", "label": "Nvidia", "group": "Recherche / formation / écosystème IA", "size": 15, "detail": "Cité comme fabricant de GPU dont les délais conditionnent les projets de calcul IA."}, 
    {"id": "Inquiétude sur l’eau", "label": "Inquiétude sur l’eau", "group": "Positions critiques / points de vigilance", "size": 19, "detail": "Point de tension majeur renforcé par les volumes d'eau requis, les risques de sécheresse, les conflits d'usage et la compatibilité avec le SAGE."}, 
    {"id": "Nappe phréatique", "label": "Nappe phréatique", "group": "Positions critiques / points de vigilance", "size": 15, "detail": "Ressource hydrique dont la capacité est interrogée au regard des usages existants et du futur projet."}, 
    {"id": "Crédibilité des porteurs de projet", "label": "Crédibilité des porteurs de projet", "group": "Positions critiques / points de vigilance", "size": 15, "detail": "Sujet soulevé par RTE : sortir de la logique premier demandeur, premier servi pour privilégier les projets réellement matures."}, 
    {"id": "Abandon de Fluidstack", "label": "Abandon de Fluidstack", "group": "Positions critiques / points de vigilance", "size": 18, "detail": "Épisode qui fragilise le plan IA français. Les sources évoquent un désaccord financier interne."}, 
    {"id": "Souveraineté numérique", "label": "Souveraineté numérique", "group": "Positions critiques / points de vigilance", "size": 18, "detail": "Argument central du projet mis en avant par le préfet, mais interrogé face aux capitaux étrangers (SoftBank)."}, 
    {"id": "Courrier picard", "label": "Courrier picard", "group": "Médias / sources cités", "size": 15, "detail": "Source locale principale sur le choix du lauréat de l’AMI, les débats de la CC2SO et les contributions d'habitants."}, 
    {"id": "La Tribune", "label": "La Tribune", "group": "Médias / sources cités", "size": 15, "detail": "Relaye l’abandon de Fluidstack et l’arbitrage économique en faveur des États-Unis."}, 
    {"id": "Le Figaro", "label": "Le Figaro", "group": "Médias / sources cités", "size": 15, "detail": "Couvre le retrait de Fluidstack et ses conséquences sur le projet de Bosquel."}, 
    {"id": "DCmag", "label": "DCmag", "group": "Médias / sources cités", "size": 15, "detail": "Le média spécialisé suit les infrastructures data centers et l’ouverture de l’AMI du Bosquel."}, 
    {"id": "L’Usine Nouvelle", "label": "L’Usine Nouvelle", "group": "Médias / sources cités", "size": 15, "detail": "Analyse la politique de raccordement électrique de RTE pour les datacenters."}, 
    {"id": "Next INpact", "label": "Next INpact", "group": "Médias / sources cités", "size": 15, "detail": "Analyse les sites Fast Track, les capacités sécurisées et les annonces gouvernementales."}, 
    {"id": "Services RTE", "label": "Services RTE", "group": "Médias / sources cités", "size": 15, "detail": "Source institutionnelle sur la pré-réservation de capacité et la prolongation du site du Bosquel."}, 
    {"id": "Camille Ego", "label": "Camille Ego", "group": "Positions critiques / points de vigilance", "size": 16, "detail": "Présidente de l'association de protection du Bosquel. Dénonce l’opacité, le manque d'information des habitants, la proximité immédiate avec les habitations, le bruit et les risques liés à l'eau."}, 
    {"id": "Association de protection du Bosquel et des villages voisins", "label": "Association de protection\ndu Bosquel", "group": "Positions critiques / points de vigilance", "size": 16, "detail": "Association locale portant les inquiétudes concrètes des riverains face aux nuisances de proximité et aux risques écologiques locaux."}, 
    {"id": "Ancien membre de la Dreal des Hauts-de-France", "label": "Ex-membre Dreal\n(Expert Anonyme)", "group": "Positions critiques / points de vigilance", "size": 15, "detail": "Expert technique anonyme. Alerte sur les volumes d'eau massifs nécessaires, la compatibilité réglementaire avec le SAGE et l'absence de traitement du sujet dans l'AMI."}, 
    {"id": "Robert Fievet", "label": "Robert Fievet", "group": "Positions critiques / points de vigilance", "size": 15, "detail": "Habitant d'Amiens, auteur d'une contribution critique nuancée. Juge le projet nécessaire mais alerte sur l'artificialisation des terres, la sécheresse et le faible ratio emplois/investissement."}, 
    {"id": "Martine Delépine", "label": "Martine Delépine", "group": "Institutions territoriales", "size": 18, "detail": "Maire du Bosquel. Prudente et inquiète, elle reconnaît la disproportion du projet, les doutes sur l'eau et l'électricité, et le risque de conflits d'usage, tout en estimant complexe de s'y opposer frontalement."}, 
    {"id": "Sylvain Charbonnier", "label": "Sylvain Charbonnier", "group": "Institutions territoriales", "size": 16, "detail": "Maire de Molliens-Dreuil. Prudent et ambigu ; il juge le montant du dédommagement transactionnel à L’Européenne 'très élevé', bien qu’estimé nécessaire pour éteindre le contentieux."}, 
    {"id": "Rollon Mouchel-Blaisot", "label": "Rollon Mouchel-Blaisot", "group": "État / acteurs publics nationaux", "size": 18, "detail": "Préfet de la Somme. Position institutionnelle très favorable ; présente le campus comme un enjeu de souveraineté et assure publiquement que l'impact sur l'eau sera minime."}, 
    {"id": "Préfecture de la Somme", "label": "Préfecture de la Somme", "group": "État / acteurs publics nationaux", "size": 18, "detail": "Administration territoriale d’État. Assure le cadrage, le suivi des procédures et porte la présentation publique officielle du projet de supercalculateur."}, 
    {"id": "Région Hauts-de-France", "label": "Région Hauts-de-France", "group": "Institutions territoriales", "size": 18, "detail": "Collectivité régionale. Partenaire clé de la CC2SO au titre de l'intérêt régional et désignée comme future cogestionnaire du fonds de dotation de 10 M€."}, 
    {"id": "Dreal des Hauts-de-France", "label": "Dreal des Hauts-de-France", "group": "État / acteurs publics nationaux", "size": 15, "detail": "Administration environnementale régionale. Citée indirectement dans le corpus via les alertes techniques d'un ex-agent (aucune prise de position officielle à ce stade)."}, 
    {"id": "Commissaire-enquêteur", "label": "Commissaire-enquêteur", "group": "État / acteurs publics nationaux", "size": 15, "detail": "Autorité de procédure indépendante. Avait rendu un avis défavorable motivé sur l'ancien projet logistique du site en raison des nuisances."}, 
    {"id": "SoftBank Group", "label": "SoftBank Group", "group": "Porteur / lauréat industriel", "size": 22, "detail": "Groupe technologique japonais mondial. Financeur et actionnaire majoritaire de la coentreprise porteuse du projet avec Sesterce ; pivot financier du dossier."}, 
    {"id": "Sesterce", "label": "Sesterce", "group": "Porteur / lauréat industriel", "size": 22, "detail": "Société française désignée comme opérateur opérationnel et réalisateur du datacenter. Fait l'objet d'interrogations sur sa surface financière réelle face au gigantisme du site."}, 
    {"id": "Masayoshi Son", "label": "Masayoshi Son", "group": "Porteur / lauréat industriel", "size": 18, "detail": "Patron-fondateur emblématique de SoftBank. A dévoilé l'envergure de l'investissement et s'est entretenu directement avec Emmanuel Macron."}, 
    {"id": "Adam Westhead", "label": "Adam Westhead", "group": "Porteur / lauréat industriel", "size": 15, "detail": "Avocat d'affaires anglais rattaché à SoftBank. Identifié par l'investigation journalistique comme dirigeant direct de la structure Silver Bands France."}, 
    {"id": "Patriarche", "label": "Patriarche", "group": "Porteur / lauréat industriel", "size": 16, "detail": "Cabinet d'architecture d'envergure sélectionné pour concevoir et superviser le futur complexe technologique du Bosquel."}, 
    {"id": "Damien Patriarche", "label": "Damien Patriarche", "group": "Porteur / lauréat industriel", "size": 15, "detail": "Architecte en chef du projet. Il défend l'intégration paysagère fine du bâti et le recours impératif à un système de refroidissement en circuit fermé."}, 
    {"id": "L’Européenne", "label": "L’Européenne", "group": "Positions critiques / points de vigilance", "size": 18, "detail": "Ancien porteur du projet de plateforme logistique sur le site. Bénéficiaire au cœur d'un accord transactionnel financier avec la CC2SO pour bloquer tout recours futur."}, 
    {"id": "Youssef El Manssouri", "label": "Youssef El Manssouri", "group": "Porteur / lauréat industriel", "size": 15, "detail": "Entrepreneur, cofondateur et dirigeant opérationnel de Sesterce impliqué dans les négociations industrielles du projet."}, 
    {"id": "Anthony Tchakerian", "label": "Anthony Tchakerian", "group": "Porteur / lauréat industriel", "size": 15, "detail": "Entrepreneur, dirigeant associé de Sesterce. Également lié à un projet parallèle implanté dans la Drôme."}, 
    {"id": "AC-DC Rovaltain", "label": "AC-DC Rovaltain", "group": "Positions critiques / points de vigilance", "size": 13, "detail": "Collectif d'opposants de la Drôme cité à titre de comparaison. A contesté un projet de Sesterce et mis en évidence un décalage sur les chiffres réels de l'emploi."}, 
    {"id": "Cloud Temple", "label": "Cloud Temple", "group": "Recherche / formation / écosystème IA", "size": 13, "detail": "Acteur de datacenter implanté dans l’Oise, mobilisé dans le corpus uniquement comme référence technique de comparaison de puissance électrique."}, 
    {"id": "Mediacités", "label": "Mediacités", "group": "Médias / sources cités", "size": 16, "detail": "Média d'investigation locale indépendant. Révélateur des clauses financières d'indemnisation avec L'Européenne, de l'opacité perçue du montage et des doutes techniques."}, 
    {"id": "ici Picardie", "label": "ici Picardie", "group": "Médias / sources cités", "size": 15, "detail": "Média de proximité. A diffusé l'interview exclusive détaillant la posture de prudence de Martine Delépine."}, 
    {"id": "France 3 Hauts-de-France", "label": "France 3 Hauts-de-France", "group": "Médias / sources cités", "size": 15, "detail": "Chaîne publique régionale. Source d'informations clés sur le calendrier de déploiement et les arbitrages préfectoraux."}, 
    {"id": "info.fr", "label": "info.fr", "group": "Médias / sources cités", "size": 12, "detail": "Portail d'actualités économiques ayant couvert les prises de parole officielles de la préfecture de la Somme."}, 
    {"id": "Bloomberg", "label": "Bloomberg", "group": "Médias / sources cités", "size": 15, "detail": "Agence d'information financière internationale. Source de référence concernant les dynamiques globales de retrait de Fluidstack."}, 
    {"id": "L’Informé", "label": "L’Informé", "group": "Médias / sources cités", "size": 15, "detail": "Média d'investigation économique ayant mis au jour le différend commercial opposant Sesterce à Mistral AI."}, 
    {"id": "Les Électrons libres", "label": "Les Électrons libres", "group": "Médias / sources cités", "size": 12, "detail": "Média spécialisé dans l'énergie. A documenté l'hypothèse d'un désaccord de nature strictement financière concernant le pivot de Fluidstack."}, 
    {"id": "actu.fr", "label": "actu.fr", "group": "Médias / sources cités", "size": 12, "detail": "Réseau d'information locale ayant apporté des précisions géographiques sur l'emprise foncière exacte de la ZAC."}
  ], 
  "links": [
    {"source": "Campus numérique et industriel du Bosquel", "target": "ZAC du Bosquel", "kind": "rôle / lien projet"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "Silver Bands France Computer Center Bosquel", "kind": "rôle / lien projet"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "Société spécifique au Bosquel", "kind": "rôle / lien projet"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "Fluidstack", "kind": "rôle / lien projet"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "CC2SO", "kind": "rôle / lien projet"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "Alain Desfosses", "kind": "rôle / lien projet"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "Laurent Snoeck", "kind": "rôle / lien projet"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "Arnaud De Monclin", "kind": "rôle / lien projet"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "Maison des Jeunes d’Hornoy-le-Bourg", "kind": "rôle / lien projet"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "État", "kind": "rôle / lien projet"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "Bercy", "kind": "rôle / lien projet"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "Anne Le Hénanff", "kind": "rôle / lien projet"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "François Bayrou", "kind": "rôle / lien projet"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "Emmanuel Macron", "kind": "rôle / lien projet"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "CRE", "kind": "rôle / lien projet"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "DGE", "kind": "rôle / lien projet"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "Business France", "kind": "rôle / lien projet"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "RTE", "kind": "rôle / lien projet"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "Nathalie Lemaître", "kind": "rôle / lien projet"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "EDF", "kind": "rôle / lien projet"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "Lignes haute tension", "kind": "rôle / lien projet"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "Étudiants amiénois", "kind": "rôle / lien projet"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "Entreprises et start-up utilisatrices", "kind": "rôle / lien projet"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "Mistral AI", "kind": "rôle / lien projet"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "Eclairion", "kind": "rôle / lien projet"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "Anthropic", "kind": "rôle / lien projet"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "Google", "kind": "rôle / lien projet"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "Nvidia", "kind": "rôle / lien projet"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "Inquiétude sur l’eau", "kind": "rôle / lien projet"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "Nappe phréatique", "kind": "rôle / lien projet"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "Crédibilité des porteurs de projet", "kind": "rôle / lien projet"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "Abandon de Fluidstack", "kind": "rôle / lien projet"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "Souveraineté numérique", "kind": "rôle / lien projet"}, 
    {"source": "CC2SO", "target": "Alain Desfosses", "kind": "interaction / rattachement"}, 
    {"source": "CC2SO", "target": "Laurent Snoeck", "kind": "interaction / rattachement"}, 
    {"source": "CC2SO", "target": "Silver Bands France Computer Center Bosquel", "kind": "interaction / rattachement"}, 
    {"source": "CC2SO", "target": "Arnaud De Monclin", "kind": "interaction / rattachement"}, 
    {"source": "CC2SO", "target": "Société spécifique au Bosquel", "kind": "interaction / rattachement"}, 
    {"source": "Silver Bands France Computer Center Bosquel", "target": "Société spécifique au Bosquel", "kind": "interaction / rattachement"}, 
    {"source": "Silver Bands France Computer Center Bosquel", "target": "Entreprises et start-up utilisatrices", "kind": "interaction / rattachement"}, 
    {"source": "Silver Bands France Computer Center Bosquel", "target": "Étudiants amiénois", "kind": "interaction / rattachement"}, 
    {"source": "Arnaud De Monclin", "target": "Inquiétude sur l’eau", "kind": "interaction / rattachement"}, 
    {"source": "Inquiétude sur l’eau", "target": "Nappe phréatique", "kind": "interaction / rattachement"}, 
    {"source": "Laurent Snoeck", "target": "Inquiétude sur l’eau", "kind": "interaction / rattachement"}, 
    {"source": "RTE", "target": "État", "kind": "interaction / rattachement"}, 
    {"source": "RTE", "target": "CRE", "kind": "interaction / rattachement"}, 
    {"source": "RTE", "target": "Nathalie Lemaître", "kind": "interaction / rattachement"}, 
    {"source": "RTE", "target": "Lignes haute tension", "kind": "interaction / rattachement"}, 
    {"source": "RTE", "target": "Crédibilité des porteurs de projet", "kind": "interaction / rattachement"}, 
    {"source": "État", "target": "Bercy", "kind": "interaction / rattachement"}, 
    {"source": "État", "target": "Anne Le Hénanff", "kind": "interaction / rattachement"}, 
    {"source": "État", "target": "DGE", "kind": "interaction / rattachement"}, 
    {"source": "État", "target": "Business France", "kind": "interaction / rattachement"}, 
    {"source": "Emmanuel Macron", "target": "État", "kind": "interaction / rattachement"}, 
    {"source": "Fluidstack", "target": "Abandon de Fluidstack", "kind": "interaction / rattachement"}, 
    {"source": "Fluidstack", "target": "Anthropic", "kind": "interaction / rattachement"}, 
    {"source": "Fluidstack", "target": "Google", "kind": "interaction / rattachement"}, 
    {"source": "Fluidstack", "target": "Mistral AI", "kind": "interaction / rattachement"}, 
    {"source": "Mistral AI", "target": "Eclairion", "kind": "interaction / rattachement"}, 
    {"source": "Nvidia", "target": "Souveraineté numérique", "kind": "interaction / rattachement"}, 
    {"source": "Souveraineté numérique", "target": "Mistral AI", "kind": "interaction / rattachement"}, 
    {"source": "Abandon de Fluidstack", "target": "Souveraineté numérique", "kind": "interaction / rattachement"}, 
    {"source": "EDF", "target": "RTE", "kind": "interaction / rattachement"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "Courrier picard", "kind": "source / couverture"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "La Tribune", "kind": "source / couverture"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "Le Figaro", "kind": "source / couverture"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "DCmag", "kind": "source / couverture"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "L’Usine Nouvelle", "kind": "source / couverture"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "Next INpact", "kind": "source / couverture"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "Services RTE", "kind": "source / couverture"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "Camille Ego", "kind": "rôle / lien projet"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "Association de protection du Bosquel et des villages voisins", "kind": "rôle / lien projet"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "Ancien membre de la Dreal des Hauts-de-France", "kind": "rôle / lien projet"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "Robert Fievet", "kind": "rôle / lien projet"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "Martine Delépine", "kind": "rôle / lien projet"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "Sylvain Charbonnier", "kind": "rôle / lien projet"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "Rollon Mouchel-Blaisot", "kind": "rôle / lien projet"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "SoftBank Group", "kind": "rôle / lien projet"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "Sesterce", "kind": "rôle / lien projet"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "Patriarche", "kind": "rôle / lien projet"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "L’Européenne", "kind": "rôle / lien projet"}, 
    {"source": "Camille Ego", "target": "Association de protection du Bosquel et des villages voisins", "kind": "interaction / rattachement"}, 
    {"source": "Association de protection du Bosquel et des villages voisins", "target": "Inquiétude sur l’eau", "kind": "interaction / rattachement"}, 
    {"source": "Ancien membre de la Dreal des Hauts-de-France", "target": "Inquiétude sur l’eau", "kind": "interaction / rattachement"}, 
    {"source": "Ancien membre de la Dreal des Hauts-de-France", "target": "Dreal des Hauts-de-France", "kind": "interaction / rattachement"}, 
    {"source": "Robert Fievet", "target": "Inquiétude sur l’eau", "kind": "interaction / rattachement"}, 
    {"source": "Martine Delépine", "target": "Inquiétude sur l’eau", "kind": "interaction / rattachement"}, 
    {"source": "Martine Delépine", "target": "CC2SO", "kind": "interaction / rattachement"}, 
    {"source": "Sylvain Charbonnier", "target": "L’Européenne", "kind": "interaction / rattachement"}, 
    {"source": "CC2SO", "target": "L’Européenne", "kind": "interaction / rattachement"}, 
    {"source": "L’Européenne", "target": "Commissaire-enquêteur", "kind": "interaction / rattachement"}, 
    {"source": "Rollon Mouchel-Blaisot", "target": "Préfecture de la Somme", "kind": "interaction / rattachement"}, 
    {"source": "Rollon Mouchel-Blaisot", "target": "Inquiétude sur l’eau", "kind": "interaction / rattachement"}, 
    {"source": "Préfecture de la Somme", "target": "État", "kind": "interaction / rattachement"}, 
    {"source": "Région Hauts-de-France", "target": "CC2SO", "kind": "interaction / rattachement"}, 
    {"source": "SoftBank Group", "target": "Sesterce", "kind": "interaction / rattachement"}, 
    {"source": "SoftBank Group", "target": "Masayoshi Son", "kind": "interaction / rattachement"}, 
    {"source": "SoftBank Group", "target": "Adam Westhead", "kind": "interaction / rattachement"}, 
    {"source": "Silver Bands France Computer Center Bosquel", "target": "Adam Westhead", "kind": "interaction / rattachement"}, 
    {"source": "Masayoshi Son", "target": "Emmanuel Macron", "kind": "interaction / rattachement"}, 
    {"source": "Sesterce", "target": "Youssef El Manssouri", "kind": "interaction / rattachement"}, 
    {"source": "Sesterce", "target": "Anthony Tchakerian", "kind": "interaction / rattachement"}, 
    {"source": "Sesterce", "target": "AC-DC Rovaltain", "kind": "interaction / rattachement"}, 
    {"source": "Sesterce", "target": "Mistral AI", "kind": "interaction / rattachement"}, 
    {"source": "Patriarche", "target": "Damien Patriarche", "kind": "interaction / rattachement"}, 
    {"source": "Damien Patriarche", "target": "Inquiétude sur l’eau", "kind": "interaction / rattachement"}, 
    {"source": "Cloud Temple", "target": "Campus numérique et industriel du Bosquel", "kind": "interaction / rattachement"}, 
    {"source": "Campus numérique et industriel du Bosquel", "target": "Mediacités", "kind": "source / couverture"}, 
    {"source": "L’Européenne", "target": "Mediacités", "kind": "source / couverture"}, 
    {"source": "Martine Delépine", "target": "ici Picardie", "kind": "source / couverture"}, 
    {"source": "Rollon Mouchel-Blaisot", "target": "France 3 Hauts-de-France", "kind": "source / couverture"}, 
    {"source": "Préfecture de la Somme", "target": "info.fr", "kind": "source / couverture"}, 
    {"source": "Fluidstack", "target": "Bloomberg", "kind": "source / couverture"}, 
    {"source": "Sesterce", "target": "L’Informé", "kind": "source / couverture"}, 
    {"source": "Mistral AI", "target": "L’Informé", "kind": "source / couverture"}, 
    {"source": "Fluidstack", "target": "Les Électrons libres", "kind": "source / couverture"}, 
    {"source": "ZAC du Bosquel", "target": "actu.fr", "kind": "source / couverture"}, 
    {"source": "Robert Fievet", "target": "Courrier picard", "kind": "source / couverture"}
  ]
};
